/**
 * ISO/IEC 27001:2022 Annex A control catalog (93 controls).
 * Bilingual EN/UK — titles and descriptions for Controls Repository.
 * Domains follow the classic ISO 27001 thematic structure (14 domains).
 */
export type Iso27001ControlSeed = {
  controlCode: string;
  titleEn: string;
  titleUk: string;
  descriptionEn: string;
  descriptionUk: string;
  categoryEn: string;
  categoryUk: string;
  source: string;
};

export const ISO27001_DOMAINS = {
  policies: {
    en: 'Information security policies',
    uk: 'Політики інформаційної безпеки',
  },
  organization: {
    en: 'Organization of information security',
    uk: 'Організація інформаційної безпеки',
  },
  humanResources: {
    en: 'Human resource security',
    uk: 'Безпека людських ресурсів',
  },
  assetManagement: {
    en: 'Asset management',
    uk: 'Управління активами',
  },
  accessControl: {
    en: 'Access control',
    uk: 'Контроль доступу',
  },
  cryptography: {
    en: 'Cryptography',
    uk: 'Кріптографія',
  },
  physicalSecurity: {
    en: 'Physical security and environmental security',
    uk: 'Фізична безпека та безпека довкілля',
  },
  operationsSecurity: {
    en: 'Operations security',
    uk: 'Операційна безпека',
  },
  communicationsSecurity: {
    en: 'Communications security',
    uk: 'Безпека комунікацій',
  },
  systemDevelopment: {
    en: 'System acquisition, development and maintenance',
    uk: 'Придбання, розробка та обслуговування систем',
  },
  supplierRelationships: {
    en: 'Supplier relationships',
    uk: 'Відносини з постачальниками',
  },
  incidentManagement: {
    en: 'Information security incident management',
    uk: 'Управління інцидентами інформаційної безпеки',
  },
  businessContinuity: {
    en: 'Information security aspects of business continuity management',
    uk: 'Аспекти управління безперервністю бізнесу',
  },
  compliance: {
    en: 'Compliance',
    uk: 'Відповідність вимогам (комплаєнс)',
  },
} as const;

export const ISO27001_DOMAIN_ORDER = Object.values(ISO27001_DOMAINS).map(
  d => `${d.en} / ${d.uk}`,
);

function parseIsoControlNumber(controlCode: string): { major: number; minor: number } {
  const match = controlCode.match(/^ISO-(\d+)\.(\d+)$/);
  if (!match) return { major: 0, minor: 0 };
  return { major: Number(match[1]), minor: Number(match[2]) };
}

/** Map ISO 27001:2022 control codes to the 14 classic thematic domains. */
export function domainForIsoControlCode(controlCode: string): { en: string; uk: string } {
  const { major, minor } = parseIsoControlNumber(controlCode);
  const d = ISO27001_DOMAINS;

  if (major === 5) {
    if (minor === 1) return d.policies;
    if (minor >= 2 && minor <= 8) return d.organization;
    if (minor >= 9 && minor <= 13) return d.assetManagement;
    if (minor === 14) return d.communicationsSecurity;
    if (minor >= 15 && minor <= 18) return d.accessControl;
    if (minor >= 19 && minor <= 23) return d.supplierRelationships;
    if (minor >= 24 && minor <= 28) return d.incidentManagement;
    if (minor >= 29 && minor <= 30) return d.businessContinuity;
    if (minor >= 31 && minor <= 37) return d.compliance;
  }
  if (major === 6) return d.humanResources;
  if (major === 7) return d.physicalSecurity;
  if (major === 8) {
    if ([2, 3, 4, 5].includes(minor)) return d.accessControl;
    if ([20, 21, 22, 23].includes(minor)) return d.communicationsSecurity;
    if (minor === 24) return d.cryptography;
    if ([25, 26, 27, 28, 29, 30, 31, 33].includes(minor)) return d.systemDevelopment;
    return d.operationsSecurity;
  }

  return { en: 'Uncategorized', uk: 'Без категорії' };
}

const ISO27001_CONTROLS_RAW: Iso27001ControlSeed[] = [
  {
    controlCode: "ISO-5.1",
    titleEn: "Policies for information security",
    titleUk: "Політики інформаційної безпеки",
    descriptionEn: "A set of policies for information security shall be defined, approved by management, published, communicated to and acknowledged by relevant personnel and relevant interested parties, and reviewed at planned intervals and if significant changes occur.",
    descriptionUk: "Набір політик інформаційної безпеки має бути визначений, затверджений керівництвом, опублікований, доведений до відома та підтверджений відповідним персоналом і зацікавленими сторонами, а також переглядатися за планом і при суттєвих змінах.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.1",
  },
  {
    controlCode: "ISO-5.2",
    titleEn: "Information security roles and responsibilities",
    titleUk: "Ролі та відповідальність у сфері інформаційної безпеки",
    descriptionEn: "Information security roles and responsibilities shall be defined and allocated according to the organization needs.",
    descriptionUk: "Ролі та відповідальність у сфері інформаційної безпеки мають бути визначені та розподілені відповідно до потреб організації.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.2",
  },
  {
    controlCode: "ISO-5.3",
    titleEn: "Segregation of duties",
    titleUk: "Розподіл обов'язків",
    descriptionEn: "Conflicting duties and conflicting areas of responsibility shall be segregated.",
    descriptionUk: "Конфліктні обов'язки та сфери відповідальності мають бути розділені.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.3",
  },
  {
    controlCode: "ISO-5.4",
    titleEn: "Management responsibilities",
    titleUk: "Відповідальність керівництва",
    descriptionEn: "Management shall require all personnel to apply information security in accordance with the established information security policy, topic-specific policies and procedures of the organization.",
    descriptionUk: "Керівництво має вимагати від усього персоналу застосування інформаційної безпеки відповідно до встановленої політики, тематичних політик і процедур організації.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.4",
  },
  {
    controlCode: "ISO-5.5",
    titleEn: "Contact with authorities",
    titleUk: "Контакти з органами влади",
    descriptionEn: "The organization shall establish and maintain contact with relevant authorities.",
    descriptionUk: "Організація має встановлювати та підтримувати контакти з відповідними органами влади.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.5",
  },
  {
    controlCode: "ISO-5.6",
    titleEn: "Contact with special interest groups",
    titleUk: "Контакти зі спеціалізованими групами",
    descriptionEn: "The organization shall establish and maintain contact with special interest groups or other specialist security forums and professional associations.",
    descriptionUk: "Організація має встановлювати та підтримувати контакти зі спеціалізованими групами, форумами з безпеки та професійними асоціаціями.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.6",
  },
  {
    controlCode: "ISO-5.7",
    titleEn: "Threat intelligence",
    titleUk: "Аналіз загроз",
    descriptionEn: "Information relating to information security threats shall be collected and analysed to produce threat intelligence.",
    descriptionUk: "Інформація щодо загроз інформаційній безпеці має збиратися та аналізуватися для формування розвідувальних даних про загрози.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.7",
  },
  {
    controlCode: "ISO-5.8",
    titleEn: "Information security in project management",
    titleUk: "Інформаційна безпека в управлінні проєктами",
    descriptionEn: "Information security shall be integrated into project management.",
    descriptionUk: "Інформаційна безпека має бути інтегрована в управління проєктами.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.8",
  },
  {
    controlCode: "ISO-5.9",
    titleEn: "Inventory of information and other associated assets",
    titleUk: "Інвентаризація інформації та пов'язаних активів",
    descriptionEn: "An inventory of information and other associated assets, including owners, shall be developed and maintained.",
    descriptionUk: "Інвентаризація інформації та пов'язаних активів, включно з власниками, має бути створена та підтримуватися.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.9",
  },
  {
    controlCode: "ISO-5.10",
    titleEn: "Acceptable use of information and other associated assets",
    titleUk: "Прийнятне використання інформації та активів",
    descriptionEn: "Rules for the acceptable use and procedures for handling information and other associated assets shall be identified, documented and implemented.",
    descriptionUk: "Правила прийнятного використання та процедури оброблення інформації й активів мають бути визначені, задокументовані та впроваджені.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.10",
  },
  {
    controlCode: "ISO-5.11",
    titleEn: "Return of assets",
    titleUk: "Повернення активів",
    descriptionEn: "Personnel and other interested parties as appropriate shall return all the organization's assets in their possession upon change or termination of their employment, contract or agreement.",
    descriptionUk: "Персонал і зацікавлені сторони мають повернути всі активи організації при зміні або припиненні трудових, договірних чи інших відносин.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.11",
  },
  {
    controlCode: "ISO-5.12",
    titleEn: "Classification of information",
    titleUk: "Класифікація інформації",
    descriptionEn: "Information shall be classified according to the information security needs of the organization based on confidentiality, integrity, availability and relevant interested party requirements.",
    descriptionUk: "Інформація має класифікуватися відповідно до потреб організації щодо конфіденційності, цілісності, доступності та вимог зацікавлених сторін.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.12",
  },
  {
    controlCode: "ISO-5.13",
    titleEn: "Labelling of information",
    titleUk: "Маркування інформації",
    descriptionEn: "An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.",
    descriptionUk: "Має бути розроблено та впроваджено відповідний набір процедур маркування інформації згідно зі схемою класифікації організації.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.13",
  },
  {
    controlCode: "ISO-5.14",
    titleEn: "Information transfer",
    titleUk: "Передавання інформації",
    descriptionEn: "Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities within the organization and between the organization and other parties.",
    descriptionUk: "Правила, процедури або угоди щодо передавання інформації мають існувати для всіх типів каналів передачі всередині організації та між організацією й третіми сторонами.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.14",
  },
  {
    controlCode: "ISO-5.15",
    titleEn: "Access control",
    titleUk: "Керування доступом",
    descriptionEn: "Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements.",
    descriptionUk: "Правила контролю фізичного та логічного доступу до інформації й активів мають бути встановлені та впроваджені на основі бізнес- та ІБ-вимог.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.15",
  },
  {
    controlCode: "ISO-5.16",
    titleEn: "Identity management",
    titleUk: "Управління ідентичностями",
    descriptionEn: "The full life cycle of identities shall be managed.",
    descriptionUk: "Повний життєвий цикл ідентичностей має управлятися.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.16",
  },
  {
    controlCode: "ISO-5.17",
    titleEn: "Authentication information",
    titleUk: "Інформація для автентифікації",
    descriptionEn: "Allocation and management of authentication information shall be controlled by a management process, including advising personnel on appropriate handling of authentication information.",
    descriptionUk: "Розподіл і управління інформацією для автентифікації мають контролюватися процесом управління, включно з інструктажем персоналу щодо належного оброблення такої інформації.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.17",
  },
  {
    controlCode: "ISO-5.18",
    titleEn: "Access rights",
    titleUk: "Права доступу",
    descriptionEn: "Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organization's topic-specific policy on and rules for access control.",
    descriptionUk: "Права доступу до інформації та активів мають надаватися, переглядатися, змінюватися та скасовуватися відповідно до політики та правил керування доступом організації.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.18",
  },
  {
    controlCode: "ISO-5.19",
    titleEn: "Information security in supplier relationships",
    titleUk: "Інформаційна безпека у відносинах із постачальниками",
    descriptionEn: "Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier's products or services.",
    descriptionUk: "Процеси та процедури мають бути визначені та впроваджені для управління ризиками ІБ, пов'язаними з використанням продуктів або послуг постачальників.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.19",
  },
  {
    controlCode: "ISO-5.20",
    titleEn: "Addressing information security within supplier agreements",
    titleUk: "Інформаційна безпека в угодах із постачальниками",
    descriptionEn: "Relevant information security requirements shall be established and agreed with each supplier based on the type of supplier relationship.",
    descriptionUk: "Відповідні вимоги ІБ мають бути встановлені та погоджені з кожним постачальником залежно від типу відносин.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.20",
  },
  {
    controlCode: "ISO-5.21",
    titleEn: "Managing information security in the ICT supply chain",
    titleUk: "Управління ІБ у ланцюгу постачання ІКТ",
    descriptionEn: "Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT products and services supply chain.",
    descriptionUk: "Процеси та процедури мають бути визначені та впроваджені для управління ризиками ІБ, пов'язаними з ланцюгом постачання ІКТ-продуктів і послуг.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.21",
  },
  {
    controlCode: "ISO-5.22",
    titleEn: "Monitoring, review and change management of supplier services",
    titleUk: "Моніторинг і перегляд послуг постачальників",
    descriptionEn: "The organization shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.",
    descriptionUk: "Організація має регулярно моніторити, переглядати, оцінювати та управляти змінами в практиках ІБ і наданні послуг постачальниками.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.22",
  },
  {
    controlCode: "ISO-5.23",
    titleEn: "Information security for use of cloud services",
    titleUk: "Інформаційна безпека при використанні хмарних сервісів",
    descriptionEn: "Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organization's information security requirements.",
    descriptionUk: "Процеси набуття, використання, управління та виходу з хмарних сервісів мають бути встановлені відповідно до вимог ІБ організації.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.23",
  },
  {
    controlCode: "ISO-5.24",
    titleEn: "Information security incident management planning and preparation",
    titleUk: "Планування реагування на інциденти ІБ",
    descriptionEn: "The organization shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.",
    descriptionUk: "Організація має планувати та готуватися до управління інцидентами ІБ, визначивши, встановивши та довівши процеси, ролі та відповідальність.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.24",
  },
  {
    controlCode: "ISO-5.25",
    titleEn: "Assessment and decision on information security events",
    titleUk: "Оцінка подій інформаційної безпеки",
    descriptionEn: "The organization shall assess information security events and decide if they are to be categorized as information security incidents.",
    descriptionUk: "Організація має оцінювати події ІБ і визначати, чи класифікувати їх як інциденти ІБ.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.25",
  },
  {
    controlCode: "ISO-5.26",
    titleEn: "Response to information security incidents",
    titleUk: "Реагування на інциденти ІБ",
    descriptionEn: "Information security incidents shall be responded to in accordance with the documented procedures.",
    descriptionUk: "На інциденти ІБ має реагуватися відповідно до задокументованих процедур.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.26",
  },
  {
    controlCode: "ISO-5.27",
    titleEn: "Learning from information security incidents",
    titleUk: "Вивчення уроків з інцидентів ІБ",
    descriptionEn: "Knowledge gained from information security incidents shall be used to strengthen and improve the information security controls.",
    descriptionUk: "Знання, отримані з інцидентів ІБ, мають використовуватися для посилення та вдосконалення контролів ІБ.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.27",
  },
  {
    controlCode: "ISO-5.28",
    titleEn: "Collection of evidence",
    titleUk: "Збір доказів",
    descriptionEn: "The organization shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.",
    descriptionUk: "Організація має встановити та впровадити процедури ідентифікації, збору, отримання та збереження доказів, пов'язаних з подіями ІБ.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.28",
  },
  {
    controlCode: "ISO-5.29",
    titleEn: "Information security during disruption",
    titleUk: "Інформаційна безпека під час порушень",
    descriptionEn: "The organization shall plan how to maintain information security at an appropriate level during disruption.",
    descriptionUk: "Організація має планувати підтримання належного рівня ІБ під час порушень діяльності.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.29",
  },
  {
    controlCode: "ISO-5.30",
    titleEn: "ICT readiness for business continuity",
    titleUk: "Готовність ІКТ до безперервності бізнесу",
    descriptionEn: "ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements.",
    descriptionUk: "Готовність ІКТ має плануватися, впроваджуватися, підтримуватися та тестуватися на основі цілей безперервності бізнесу та вимог до ІКТ.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.30",
  },
  {
    controlCode: "ISO-5.31",
    titleEn: "Legal, statutory, regulatory and contractual requirements",
    titleUk: "Правові, нормативні та договірні вимоги",
    descriptionEn: "Legal, statutory, regulatory and contractual requirements relevant to information security and the organization's approach to meet these requirements shall be identified, documented and kept up to date.",
    descriptionUk: "Правові, нормативні та договірні вимоги щодо ІБ та підхід організації до їх виконання мають бути ідентифіковані, задокументовані та актуалізовані.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.31",
  },
  {
    controlCode: "ISO-5.32",
    titleEn: "Intellectual property rights",
    titleUk: "Права інтелектуальної власності",
    descriptionEn: "The organization shall implement appropriate procedures to protect intellectual property rights.",
    descriptionUk: "Організація має впровадити відповідні процедури захисту прав інтелектуальної власності.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.32",
  },
  {
    controlCode: "ISO-5.33",
    titleEn: "Protection of records",
    titleUk: "Захист записів",
    descriptionEn: "Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release.",
    descriptionUk: "Записи мають бути захищені від втрати, знищення, фальсифікації, несанкціонованого доступу та розкриття.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.33",
  },
  {
    controlCode: "ISO-5.34",
    titleEn: "Privacy and protection of PII",
    titleUk: "Конфіденційність та захист PII",
    descriptionEn: "The organization shall identify and meet the requirements regarding the preservation of privacy and protection of PII according to applicable laws and regulations and contractual requirements.",
    descriptionUk: "Організація має визначати та виконувати вимоги щодо збереження конфіденційності та захисту PII згідно із законодавством, нормативами та договорами.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.34",
  },
  {
    controlCode: "ISO-5.35",
    titleEn: "Independent information security reviews",
    titleUk: "Незалежні перегляди ІБ",
    descriptionEn: "The organization's approach to managing information security and its implementation including people, processes and technologies shall be reviewed independently at planned intervals, or when significant changes occur.",
    descriptionUk: "Підхід організації до управління ІБ та його реалізація мають незалежно переглядатися за планом або при суттєвих змінах.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.35",
  },
  {
    controlCode: "ISO-5.36",
    titleEn: "Compliance with policies, rules and standards",
    titleUk: "Відповідність політикам і стандартам",
    descriptionEn: "Compliance with the organization's information security policy, topic-specific policies, rules and standards shall be regularly reviewed.",
    descriptionUk: "Відповідність політиці ІБ, тематичним політикам, правилам і стандартам організації має регулярно переглядатися.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.36",
  },
  {
    controlCode: "ISO-5.37",
    titleEn: "Documented operating procedures",
    titleUk: "Задокументовані операційні процедури",
    descriptionEn: "Operating procedures for information processing facilities shall be documented and made available to personnel who need them.",
    descriptionUk: "Операційні процедури для обробних засобів інформації мають бути задокументовані та доступні персоналу, якому вони потрібні.",
    categoryEn: "A.5 Organizational controls",
    categoryUk: "A.5 Організаційні контролі",
    source: "ISO/IEC 27001:2022 Annex A 5.37",
  },
  {
    controlCode: "ISO-6.1",
    titleEn: "Screening",
    titleUk: "Перевірка кандидатів",
    descriptionEn: "Background verification checks on all candidates to become personnel shall be carried out prior to joining the organization and on an ongoing basis taking into consideration applicable laws, regulations and ethics and be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.",
    descriptionUk: "Перевірка кандидатів перед прийняттям на роботу та на постійній основі має проводитися з урахуванням законодавства, етики, бізнес-вимог, класифікації інформації та ризиків.",
    categoryEn: "A.6 People controls",
    categoryUk: "A.6 Контролі персоналу",
    source: "ISO/IEC 27001:2022 Annex A 6.1",
  },
  {
    controlCode: "ISO-6.2",
    titleEn: "Terms and conditions of employment",
    titleUk: "Умови працевлаштування",
    descriptionEn: "The employment contractual agreements shall state the personnel's and the organization's responsibilities for information security.",
    descriptionUk: "Трудові або договірні угоди мають визначати відповідальність персоналу та організації щодо інформаційної безпеки.",
    categoryEn: "A.6 People controls",
    categoryUk: "A.6 Контролі персоналу",
    source: "ISO/IEC 27001:2022 Annex A 6.2",
  },
  {
    controlCode: "ISO-6.3",
    titleEn: "Information security awareness, education and training",
    titleUk: "Обізнаність, навчання та тренінги з ІБ",
    descriptionEn: "Personnel of the organization and relevant interested parties shall receive appropriate information security awareness, education and training and regular updates of the organization's information security policy, topic-specific policies and procedures, as relevant for their job function.",
    descriptionUk: "Персонал і зацікавлені сторони мають отримувати відповідне навчання з ІБ та регулярні оновлення політик і процедур відповідно до їхніх функцій.",
    categoryEn: "A.6 People controls",
    categoryUk: "A.6 Контролі персоналу",
    source: "ISO/IEC 27001:2022 Annex A 6.3",
  },
  {
    controlCode: "ISO-6.4",
    titleEn: "Disciplinary process",
    titleUk: "Дисциплінарний процес",
    descriptionEn: "A disciplinary process shall be formalized and communicated to take actions against personnel and other relevant interested parties who have committed an information security policy violation.",
    descriptionUk: "Дисциплінарний процес має бути формалізований і доведений для реагування на порушення політики ІБ.",
    categoryEn: "A.6 People controls",
    categoryUk: "A.6 Контролі персоналу",
    source: "ISO/IEC 27001:2022 Annex A 6.4",
  },
  {
    controlCode: "ISO-6.5",
    titleEn: "Responsibilities after termination or change of employment",
    titleUk: "Обов'язки після звільнення або зміни посади",
    descriptionEn: "Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated to relevant personnel and other interested parties.",
    descriptionUk: "Обов'язки з ІБ, що залишаються чинними після звільнення або зміни посади, мають бути визначені, забезпечені та доведені.",
    categoryEn: "A.6 People controls",
    categoryUk: "A.6 Контролі персоналу",
    source: "ISO/IEC 27001:2022 Annex A 6.5",
  },
  {
    controlCode: "ISO-6.6",
    titleEn: "Confidentiality or non-disclosure agreements",
    titleUk: "Угоди про конфіденційність",
    descriptionEn: "Confidentiality or non-disclosure agreements reflecting the organization's needs for the protection of information shall be identified, documented, regularly reviewed and signed by personnel and other relevant interested parties.",
    descriptionUk: "Угоди про конфіденційність мають бути ідентифіковані, задокументовані, регулярно переглядатися та підписуватися персоналом і зацікавленими сторонами.",
    categoryEn: "A.6 People controls",
    categoryUk: "A.6 Контролі персоналу",
    source: "ISO/IEC 27001:2022 Annex A 6.6",
  },
  {
    controlCode: "ISO-6.7",
    titleEn: "Remote working",
    titleUk: "Віддалена робота",
    descriptionEn: "Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organization's premises.",
    descriptionUk: "Заходи безпеки мають впроваджуватися під час віддаленої роботи для захисту інформації поза приміщеннями організації.",
    categoryEn: "A.6 People controls",
    categoryUk: "A.6 Контролі персоналу",
    source: "ISO/IEC 27001:2022 Annex A 6.7",
  },
  {
    controlCode: "ISO-6.8",
    titleEn: "Information security event reporting",
    titleUk: "Повідомлення про події ІБ",
    descriptionEn: "The organization shall provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner.",
    descriptionUk: "Організація має забезпечити механізм своєчасного повідомлення персоналом про спостережувані або підозрювані події ІБ.",
    categoryEn: "A.6 People controls",
    categoryUk: "A.6 Контролі персоналу",
    source: "ISO/IEC 27001:2022 Annex A 6.8",
  },
  {
    controlCode: "ISO-7.1",
    titleEn: "Physical security perimeters",
    titleUk: "Фізичні периметри безпеки",
    descriptionEn: "Security perimeters shall be defined and used to protect areas that contain information and other associated assets.",
    descriptionUk: "Периметри безпеки мають бути визначені та використовуватися для захисту зон із інформацією та активами.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.1",
  },
  {
    controlCode: "ISO-7.2",
    titleEn: "Physical entry",
    titleUk: "Фізичний вхід",
    descriptionEn: "Secure areas shall be protected by appropriate entry controls and access points.",
    descriptionUk: "Захищені зони мають бути обладнані належним контролем входу та точками доступу.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.2",
  },
  {
    controlCode: "ISO-7.3",
    titleEn: "Securing offices, rooms and facilities",
    titleUk: "Захист офісів, приміщень і об'єктів",
    descriptionEn: "Physical security for offices, rooms and facilities shall be designed and implemented.",
    descriptionUk: "Фізична безпека офісів, приміщень і об'єктів має бути спроєктована та впроваджена.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.3",
  },
  {
    controlCode: "ISO-7.4",
    titleEn: "Physical security monitoring",
    titleUk: "Фізичний моніторинг безпеки",
    descriptionEn: "Premises shall be continuously monitored for unauthorized physical access.",
    descriptionUk: "Приміщення мають постійно моніторитися на предмет несанкціонованого фізичного доступу.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.4",
  },
  {
    controlCode: "ISO-7.5",
    titleEn: "Protecting against physical and environmental threats",
    titleUk: "Захист від фізичних і екологічних загроз",
    descriptionEn: "Protection against physical and environmental threats, such as natural disaster and other intentional or unintentional physical threats to infrastructure shall be designed and implemented.",
    descriptionUk: "Захист від фізичних і екологічних загроз має бути спроєктований та впроваджений.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.5",
  },
  {
    controlCode: "ISO-7.6",
    titleEn: "Working in secure areas",
    titleUk: "Робота в захищених зонах",
    descriptionEn: "Security measures for working in secure areas shall be designed and implemented.",
    descriptionUk: "Заходи безпеки для роботи в захищених зонах мають бути спроєктовані та впроваджені.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.6",
  },
  {
    controlCode: "ISO-7.7",
    titleEn: "Clear desk and clear screen",
    titleUk: "Чистий стіл і чистий екран",
    descriptionEn: "Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and appropriately enforced.",
    descriptionUk: "Правила чистого столу та чистого екрана мають бути визначені та належним чином забезпечені.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.7",
  },
  {
    controlCode: "ISO-7.8",
    titleEn: "Equipment siting and protection",
    titleUk: "Розміщення та захист обладнання",
    descriptionEn: "Equipment shall be sited securely and protected.",
    descriptionUk: "Обладнання має бути безпечно розміщене та захищене.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.8",
  },
  {
    controlCode: "ISO-7.9",
    titleEn: "Security of assets off-premises",
    titleUk: "Безпека активів поза приміщеннями",
    descriptionEn: "Off-site assets shall be protected.",
    descriptionUk: "Активи поза приміщеннями організації мають бути захищені.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.9",
  },
  {
    controlCode: "ISO-7.10",
    titleEn: "Storage media",
    titleUk: "Носії інформації",
    descriptionEn: "Storage media shall be managed through their life cycle of acquisition, use, transportation and disposal in accordance with the organization's classification scheme and handling requirements.",
    descriptionUk: "Носії інформації мають управлятися протягом життєвого циклу відповідно до схеми класифікації та вимог оброблення.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.10",
  },
  {
    controlCode: "ISO-7.11",
    titleEn: "Supporting utilities",
    titleUk: "Інженерні системи",
    descriptionEn: "Information processing facilities shall be protected from power failures and other disruptions caused by failures in supporting utilities.",
    descriptionUk: "Обробні засоби інформації мають бути захищені від збоїв живлення та інших порушень інженерних систем.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.11",
  },
  {
    controlCode: "ISO-7.12",
    titleEn: "Cabling security",
    titleUk: "Безпека кабельних систем",
    descriptionEn: "Cables carrying power, data or supporting information services shall be protected from interception, interference or damage.",
    descriptionUk: "Кабелі, що передають живлення, дані або підтримують інформаційні сервіси, мають бути захищені від перехоплення, перешкод або пошкоджень.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.12",
  },
  {
    controlCode: "ISO-7.13",
    titleEn: "Equipment maintenance",
    titleUk: "Обслуговування обладнання",
    descriptionEn: "Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information.",
    descriptionUk: "Обладнання має належно обслуговуватися для забезпечення доступності, цілісності та конфіденційності інформації.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.13",
  },
  {
    controlCode: "ISO-7.14",
    titleEn: "Secure disposal or re-use of equipment",
    titleUk: "Безпечна утилізація або повторне використання обладнання",
    descriptionEn: "Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.",
    descriptionUk: "Обладнання з носіями даних має перевірятися на видалення або безпечне перезаписування чутливих даних і ліцензійного ПЗ перед утилізацією або повторним використанням.",
    categoryEn: "A.7 Physical controls",
    categoryUk: "A.7 Фізичні контролі",
    source: "ISO/IEC 27001:2022 Annex A 7.14",
  },
  {
    controlCode: "ISO-8.1",
    titleEn: "User endpoint devices",
    titleUk: "Кінцеві пристрої користувачів",
    descriptionEn: "Information stored on, processed by or accessible via user endpoint devices shall be protected.",
    descriptionUk: "Інформація на кінцевих пристроях користувачів або доступна через них має бути захищена.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.1",
  },
  {
    controlCode: "ISO-8.2",
    titleEn: "Privileged access rights",
    titleUk: "Привілейовані права доступу",
    descriptionEn: "The allocation and use of privileged access rights shall be restricted and managed.",
    descriptionUk: "Надання та використання привілейованих прав доступу мають бути обмежені та керовані.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.2",
  },
  {
    controlCode: "ISO-8.3",
    titleEn: "Information access restriction",
    titleUk: "Обмеження доступу до інформації",
    descriptionEn: "Access to information and other associated assets shall be restricted in accordance with the established topic-specific policy on access control.",
    descriptionUk: "Доступ до інформації та активів має бути обмежений відповідно до політики керування доступом.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.3",
  },
  {
    controlCode: "ISO-8.4",
    titleEn: "Access to source code",
    titleUk: "Доступ до вихідного коду",
    descriptionEn: "Read and write access to source code, development tools and software libraries shall be appropriately managed.",
    descriptionUk: "Доступ на читання та запис до вихідного коду, інструментів розробки та бібліотек має належно управлятися.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.4",
  },
  {
    controlCode: "ISO-8.5",
    titleEn: "Secure authentication",
    titleUk: "Безпечна автентифікація",
    descriptionEn: "Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control.",
    descriptionUk: "Безпечні технології та процедури автентифікації мають впроваджуватися відповідно до обмежень доступу та політики.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.5",
  },
  {
    controlCode: "ISO-8.6",
    titleEn: "Capacity management",
    titleUk: "Управління потужностями",
    descriptionEn: "The use of resources shall be monitored and adjusted in line with current and expected capacity requirements.",
    descriptionUk: "Використання ресурсів має моніторитися та коригуватися відповідно до поточних і очікуваних вимог до потужностей.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.6",
  },
  {
    controlCode: "ISO-8.7",
    titleEn: "Protection against malware",
    titleUk: "Захист від шкідливого ПЗ",
    descriptionEn: "Protection against malware shall be implemented and supported by appropriate user awareness.",
    descriptionUk: "Захист від шкідливого ПЗ має бути впроваджений і підтриманий відповідною обізнаністю користувачів.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.7",
  },
  {
    controlCode: "ISO-8.8",
    titleEn: "Management of technical vulnerabilities",
    titleUk: "Управління технічними вразливостями",
    descriptionEn: "Information about technical vulnerabilities of information systems in use shall be obtained, the organization's exposure to such vulnerabilities shall be evaluated and appropriate measures shall be taken.",
    descriptionUk: "Інформація про технічні вразливості має отримуватися, оцінюватися експозиція організації та вживатися відповідні заходи.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.8",
  },
  {
    controlCode: "ISO-8.9",
    titleEn: "Configuration management",
    titleUk: "Управління конфігураціями",
    descriptionEn: "Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed.",
    descriptionUk: "Конфігурації, включно з безпековими, мають встановлюватися, документуватися, впроваджуватися, моніторитися та переглядатися.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.9",
  },
  {
    controlCode: "ISO-8.10",
    titleEn: "Information deletion",
    titleUk: "Видалення інформації",
    descriptionEn: "Information stored in information systems, devices or in any other storage media shall be deleted when no longer required.",
    descriptionUk: "Інформація має видалятися, коли вона більше не потрібна.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.10",
  },
  {
    controlCode: "ISO-8.11",
    titleEn: "Data masking",
    titleUk: "Маскування даних",
    descriptionEn: "Data masking shall be used in accordance with the organization's topic-specific policy on access control and other related topic-specific policies, and business requirements, taking applicable legislation into consideration.",
    descriptionUk: "Маскування даних має застосовуватися відповідно до політик доступу, бізнес-вимог і законодавства.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.11",
  },
  {
    controlCode: "ISO-8.12",
    titleEn: "Data leakage prevention",
    titleUk: "Запобігання витоку даних",
    descriptionEn: "Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information.",
    descriptionUk: "Заходи запобігання витоку даних мають застосовуватися до систем, мереж і пристроїв, що обробляють чутливу інформацію.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.12",
  },
  {
    controlCode: "ISO-8.13",
    titleEn: "Information backup",
    titleUk: "Резервне копіювання інформації",
    descriptionEn: "Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed topic-specific policy on backup.",
    descriptionUk: "Резервні копії інформації, ПЗ та систем мають підтримуватися та регулярно тестуватися відповідно до політики резервного копіювання.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.13",
  },
  {
    controlCode: "ISO-8.14",
    titleEn: "Redundancy of information processing facilities",
    titleUk: "Резервування обробних засобів",
    descriptionEn: "Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.",
    descriptionUk: "Обробні засоби інформації мають мати достатнє резервування для забезпечення вимог доступності.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.14",
  },
  {
    controlCode: "ISO-8.15",
    titleEn: "Logging",
    titleUk: "Журналювання",
    descriptionEn: "Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed.",
    descriptionUk: "Журнали подій, винятків, збоїв та інших релевантних подій мають створюватися, зберігатися, захищатися та аналізуватися.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.15",
  },
  {
    controlCode: "ISO-8.16",
    titleEn: "Monitoring activities",
    titleUk: "Моніторинг діяльності",
    descriptionEn: "Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents.",
    descriptionUk: "Мережі, системи та застосунки мають моніторитися на аномальну поведінку з подальшою оцінкою потенційних інцидентів ІБ.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.16",
  },
  {
    controlCode: "ISO-8.17",
    titleEn: "Clock synchronization",
    titleUk: "Синхронізація часу",
    descriptionEn: "The clocks of information processing systems used by the organization shall be synchronized to approved time sources.",
    descriptionUk: "Годинники інформаційних систем організації мають синхронізуватися з затвердженими джерелами часу.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.17",
  },
  {
    controlCode: "ISO-8.18",
    titleEn: "Use of privileged utility programs",
    titleUk: "Використання привілейованих утиліт",
    descriptionEn: "The use of utility programs that can be capable of overriding system and application controls shall be restricted and tightly controlled.",
    descriptionUk: "Використання привілейованих утиліт, здатних обходити системні та прикладні контролі, має бути обмежене та суворо контрольоване.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.18",
  },
  {
    controlCode: "ISO-8.19",
    titleEn: "Installation of software on operational systems",
    titleUk: "Встановлення ПЗ на експлуатаційні системи",
    descriptionEn: "Procedures and measures shall be implemented to securely manage software installation on operational systems.",
    descriptionUk: "Процедури та заходи мають бути впроваджені для безпечного встановлення ПЗ на експлуатаційні системи.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.19",
  },
  {
    controlCode: "ISO-8.20",
    titleEn: "Networks security",
    titleUk: "Безпека мереж",
    descriptionEn: "Networks and network devices shall be secured, managed and controlled to protect information in systems and applications.",
    descriptionUk: "Мережі та мережеві пристрої мають бути захищені, керовані та контрольовані для захисту інформації в системах і застосунках.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.20",
  },
  {
    controlCode: "ISO-8.21",
    titleEn: "Security of network services",
    titleUk: "Безпека мережевих сервісів",
    descriptionEn: "Security mechanisms, service levels and service requirements of network services shall be identified, implemented and monitored.",
    descriptionUk: "Механізми безпеки, рівні та вимоги до мережевих сервісів мають бути ідентифіковані, впроваджені та моніторитися.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.21",
  },
  {
    controlCode: "ISO-8.22",
    titleEn: "Segregation of networks",
    titleUk: "Сегментація мереж",
    descriptionEn: "Groups of information services, users and information systems shall be segregated in the organization's networks.",
    descriptionUk: "Групи інформаційних сервісів, користувачів і систем мають бути сегментовані в мережах організації.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.22",
  },
  {
    controlCode: "ISO-8.23",
    titleEn: "Web filtering",
    titleUk: "Веб-фільтрація",
    descriptionEn: "Access to external websites shall be managed to reduce exposure to malicious content.",
    descriptionUk: "Доступ до зовнішніх вебсайтів має управлятися для зменшення експозиції до шкідливого контенту.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.23",
  },
  {
    controlCode: "ISO-8.24",
    titleEn: "Use of cryptography",
    titleUk: "Використання криптографії",
    descriptionEn: "Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.",
    descriptionUk: "Правила ефективного використання криптографії, включно з управлінням ключами, мають бути визначені та впроваджені.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.24",
  },
  {
    controlCode: "ISO-8.25",
    titleEn: "Secure development life cycle",
    titleUk: "Безпечний життєвий цикл розробки",
    descriptionEn: "Rules for the secure development of software and systems shall be established and applied.",
    descriptionUk: "Правила безпечної розробки ПЗ та систем мають бути встановлені та застосовуватися.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.25",
  },
  {
    controlCode: "ISO-8.26",
    titleEn: "Application security requirements",
    titleUk: "Вимоги безпеки застосунків",
    descriptionEn: "Information security requirements shall be identified, specified and approved when developing or acquiring applications.",
    descriptionUk: "Вимоги ІБ мають ідентифікуватися, визначатися та затверджуватися під час розробки або набуття застосунків.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.26",
  },
  {
    controlCode: "ISO-8.27",
    titleEn: "Secure system architecture and engineering principles",
    titleUk: "Безпечна архітектура та інженерні принципи",
    descriptionEn: "Principles for engineering secure systems shall be established, documented, maintained and applied to any information system development activities.",
    descriptionUk: "Принципи інженерії безпечних систем мають бути встановлені, задокументовані, підтримуватися та застосовуватися.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.27",
  },
  {
    controlCode: "ISO-8.28",
    titleEn: "Secure coding",
    titleUk: "Безпечне програмування",
    descriptionEn: "Secure coding principles shall be applied to software development.",
    descriptionUk: "Принципи безпечного програмування мають застосовуватися під час розробки ПЗ.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.28",
  },
  {
    controlCode: "ISO-8.29",
    titleEn: "Security testing in development and acceptance",
    titleUk: "Тестування безпеки в розробці та приймальних випробуваннях",
    descriptionEn: "Security testing processes shall be defined and implemented in the development life cycle.",
    descriptionUk: "Процеси тестування безпеки мають бути визначені та впроваджені в життєвому циклі розробки.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.29",
  },
  {
    controlCode: "ISO-8.30",
    titleEn: "Outsourced development",
    titleUk: "Зовнішня розробка",
    descriptionEn: "The organization shall direct, monitor and review the activities related to outsourced system development.",
    descriptionUk: "Організація має керувати, моніторити та переглядати діяльність із зовнішньої розробки систем.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.30",
  },
  {
    controlCode: "ISO-8.31",
    titleEn: "Separation of development, test and production environments",
    titleUk: "Розділення середовищ розробки, тесту та продакшену",
    descriptionEn: "Development, testing and production environments shall be separated and secured.",
    descriptionUk: "Середовища розробки, тестування та експлуатації мають бути розділені та захищені.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.31",
  },
  {
    controlCode: "ISO-8.32",
    titleEn: "Change management",
    titleUk: "Управління змінами",
    descriptionEn: "Changes to information processing facilities and information systems shall be subject to change management procedures.",
    descriptionUk: "Зміни до обробних засобів і інформаційних систем мають підлягати процедурам управління змінами.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.32",
  },
  {
    controlCode: "ISO-8.33",
    titleEn: "Test information",
    titleUk: "Тестова інформація",
    descriptionEn: "Test information shall be appropriately selected, protected and managed.",
    descriptionUk: "Тестова інформація має належним чином обиратися, захищатися та управлятися.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.33",
  },
  {
    controlCode: "ISO-8.34",
    titleEn: "Protection of information systems during audit testing",
    titleUk: "Захист систем під час аудиторського тестування",
    descriptionEn: "Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management.",
    descriptionUk: "Аудиторські тести та інші перевірки експлуатаційних систем мають плануватися та погоджуватися між тестувальником і керівництвом.",
    categoryEn: "A.8 Technological controls",
    categoryUk: "A.8 Технологічні контролі",
    source: "ISO/IEC 27001:2022 Annex A 8.34",
  },
];

export const ISO27001_CONTROLS: Iso27001ControlSeed[] = ISO27001_CONTROLS_RAW.map(control => {
  const domain = domainForIsoControlCode(control.controlCode);
  return {
    ...control,
    categoryEn: domain.en,
    categoryUk: domain.uk,
  };
});
