import { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react';
import {
  GRCTask, GRCControl, Policy, GRCDocument, AutomatedCheck,
  Milestone, Integration, ChatMessage,
} from '../types';
import { apiFetch } from '../lib/api';

interface ComplianceContextType {
  tasks: GRCTask[];
  controls: GRCControl[];
  policies: Policy[];
  documents: GRCDocument[];
  checks: AutomatedCheck[];
  milestones: Milestone[];
  integrations: Integration[];
  chatMessages: ChatMessage[];

  addTask: (t: Omit<GRCTask, 'id' | 'createdAt' | 'updatedAt'>) => GRCTask;
  updateTask: (id: string, t: Partial<GRCTask>) => void;
  deleteTask: (id: string) => void;

  addControl: (c: Omit<GRCControl, 'id' | 'createdAt' | 'updatedAt'>) => void;
  updateControl: (id: string, c: Partial<GRCControl>) => void;
  deleteControl: (id: string) => void;

  addPolicy: (p: Omit<Policy, 'id' | 'createdAt' | 'updatedAt'>) => void;
  updatePolicy: (id: string, p: Partial<Policy>) => void;
  deletePolicy: (id: string) => void;

  addDocument: (d: Omit<GRCDocument, 'id'>) => void;
  deleteDocument: (id: string) => void;

  addMilestone: (m: Omit<Milestone, 'id'>) => void;
  updateMilestone: (id: string, m: Partial<Milestone>) => void;

  updateIntegration: (id: string, d: Partial<Integration>) => void;

  addChatMessage: (m: Omit<ChatMessage, 'id' | 'timestamp'>) => void;
  clearChat: () => void;
}

const ComplianceContext = createContext<ComplianceContextType | undefined>(undefined);

function genId() { return Date.now().toString(36) + Math.random().toString(36).substr(2); }

const SEED_TASKS: GRCTask[] = [
  { id: genId(), title: 'Implement access control policy', description: 'Define and implement RBAC for all systems', status: 'completed', priority: 'high', framework: 'ISO 27001', category: 'Access Control', assignee: 'Ivan Petrenko', dueDate: '2026-06-15', createdAt: '2026-01-10T10:00:00Z', updatedAt: '2026-06-14T16:00:00Z' },
  { id: genId(), title: 'Conduct risk assessment', description: 'Perform annual IT risk assessment', status: 'in_progress', priority: 'critical', framework: 'ISO 27001', category: 'Risk Management', assignee: 'Maria Koval', dueDate: '2026-08-01', createdAt: '2026-03-01T09:00:00Z', updatedAt: '2026-06-20T11:00:00Z' },
  { id: genId(), title: 'DPIA for new CRM system', description: 'Data Protection Impact Assessment', status: 'remaining', priority: 'high', framework: 'GDPR', category: 'Privacy', assignee: 'Olena Shevchenko', dueDate: '2026-09-01', createdAt: '2026-05-01T08:00:00Z', updatedAt: '2026-05-01T08:00:00Z' },
  { id: genId(), title: 'Review third-party contracts', description: 'Update vendor agreements per DORA requirements', status: 'remaining', priority: 'medium', framework: 'DORA', category: 'TPRM', assignee: 'Andriy Bondar', dueDate: '2026-10-01', createdAt: '2026-04-15T10:00:00Z', updatedAt: '2026-04-15T10:00:00Z' },
  { id: genId(), title: 'PCI DSS SAQ completion', description: 'Complete Self-Assessment Questionnaire D', status: 'completed', priority: 'high', framework: 'PCI DSS', category: 'Compliance', assignee: 'Ivan Petrenko', dueDate: '2026-05-01', createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-04-28T10:00:00Z' },
  { id: genId(), title: 'Phishing awareness training', description: 'Annual security awareness training for all staff', status: 'due_soon', priority: 'medium', framework: 'ISO 27001', category: 'Awareness', assignee: 'Svitlana Tkachenko', dueDate: '2026-07-10', createdAt: '2026-06-01T10:00:00Z', updatedAt: '2026-06-25T10:00:00Z' },
  { id: genId(), title: 'Vulnerability scan - Q3', description: 'Run quarterly vulnerability scan on all external systems', status: 'overdue', priority: 'high', framework: 'NIST CSF', category: 'Technical', assignee: 'Dmytro Kovalenko', dueDate: '2026-06-01', createdAt: '2026-05-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'SOC 2 Type II readiness', description: 'Prepare evidence collection for SOC 2 audit', status: 'in_progress', priority: 'high', framework: 'SOC 2', category: 'Audit', assignee: 'Maria Koval', dueDate: '2026-12-01', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-06-15T10:00:00Z' },
  { id: genId(), title: 'Update BCP documentation', description: 'Review and update Business Continuity Plan', status: 'remaining', priority: 'medium', framework: 'NBU Resolution №143', category: 'BCP', assignee: 'Andriy Bondar', dueDate: '2026-11-01', createdAt: '2026-06-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'NBU №95 compliance gap analysis', description: 'Identify gaps against NBU Resolution №95 requirements', status: 'in_progress', priority: 'high', framework: 'NBU Resolution №95', category: 'Compliance', assignee: 'Olena Shevchenko', dueDate: '2026-08-15', createdAt: '2026-05-15T10:00:00Z', updatedAt: '2026-06-20T10:00:00Z' },
];

const SEED_CONTROLS: GRCControl[] = [
  // === ISO 27001 Annex A Controls ===
  { id: genId(), title: 'A.5 Information Security Policies', description: 'Policy framework for information security management', framework: 'ISO 27001', category: 'Policies', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['IS_Policy_v3.pdf', 'Policy_Acceptance.xlsx'], evidenceLinks: ['https://novapay-confluence/policy/is-policy'], attachments: ['IS_Policy_v3.pdf'], controlDesign: 'NovaPay: Політика інформаційної безпеки затверджена наглядовою радою, розміщена в Confluence, щорічний перегляд', source: 'ISO 27001 A.5.1', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-01-01T10:00:00Z' }, { email: 'm.koval@novapay.ua', role: 'reviewer', name: 'Maria Koval', addedAt: '2025-01-15T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'A.6 Organization of Information Security', description: 'Internal organization, roles and responsibilities for IS', framework: 'ISO 27001', category: 'Organization', status: 'implemented', owner: 'Maria Koval', evidence: ['RACI_Matrix.xlsx', 'Org_Chart.pdf'], evidenceLinks: ['https://novapay-wiki/organization/security-roles'], attachments: [], controlDesign: 'NovaPay: Призначено CISO, створено комітет з інформаційної безпеки, розподілено ролі та відповідальність', source: 'ISO 27001 A.6.1', accessList: [{ email: 'm.koval@novapay.ua', role: 'owner', name: 'Maria Koval', addedAt: '2025-02-01T10:00:00Z' }], lastReviewed: '2026-05-15', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-05-15T10:00:00Z' },
  { id: genId(), title: 'A.7 Human Resource Security', description: 'Screening, onboarding, awareness and offboarding controls', framework: 'ISO 27001', category: 'HR', status: 'implemented', owner: 'Olena Shevchenko', evidence: ['NDA_Template.docx', 'Training_Records.xlsx'], evidenceLinks: ['https://novapay-hr/security/onboarding'], attachments: [], controlDesign: 'NovaPay: Впроваджено NDAs, перевірка фону, обов\'язкове навчання з ІБ при онбордингу, процедура звільнення', source: 'ISO 27001 A.7.1-A.7.3', accessList: [{ email: 'o.shevchenko@novapay.ua', role: 'owner', name: 'Olena Shevchenko', addedAt: '2025-01-15T10:00:00Z' }], lastReviewed: '2026-04-20', createdAt: '2025-01-15T10:00:00Z', updatedAt: '2026-04-20T10:00:00Z' },
  { id: genId(), title: 'A.8 Asset Management', description: 'Inventory, classification, ownership and handling of assets', framework: 'ISO 27001', category: 'Asset Management', status: 'in_progress', owner: 'Dmytro Kovalenko', evidence: ['Asset_Register.xlsx', 'Classification_Scheme.pdf'], evidenceLinks: ['https://novapay-cmdb/assets'], attachments: ['Asset_Register_v2.xlsx'], controlDesign: 'NovaPay: Впроваджено CMDB в ServiceNow, класифікація активів за конфіденційністю, цілісністю та доступністю', source: 'ISO 27001 A.8.1-A.8.3', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-03-01T10:00:00Z' }, { email: 'a.bondar@novapay.ua', role: 'viewer', name: 'Andriy Bondar', addedAt: '2025-03-15T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'A.9 Access Control', description: 'Business requirements, user access management, responsibilities', framework: 'ISO 27001', category: 'Access Control', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['Access_Policy.pdf', 'Access_Review_Q2.xlsx'], evidenceLinks: ['https://novapay-idm/access-policies'], attachments: ['Access_Review_Q2.xlsx'], controlDesign: 'NovaPay: RBAC через Azure AD, щоквартальний перегляд доступу, MFA для всіх користувачів, JIT доступ для адмінів', source: 'ISO 27001 A.9.1-A.9.4', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-01-01T10:00:00Z' }, { email: 'd.kovalenko@novapay.ua', role: 'implementer', name: 'Dmytro Kovalenko', addedAt: '2025-01-10T10:00:00Z' }], lastReviewed: '2026-06-10', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-06-10T10:00:00Z' },
  { id: genId(), title: 'A.10 Cryptography', description: 'Cryptographic controls and key management', framework: 'ISO 27001', category: 'Cryptography', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Crypto_Policy.pdf', 'Key_Management_Procedure.docx'], evidenceLinks: ['https://novapay-wiki/security/cryptography'], attachments: [], controlDesign: 'NovaPay: TLS 1.3 для всіх сервісів, AES-256 для даних у спокої, HSM для ключів, ротація кожні 90 днів', source: 'ISO 27001 A.10.1', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-02-01T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'A.11 Physical & Environmental Security', description: 'Secure areas, equipment security and environmental controls', framework: 'ISO 27001', category: 'Physical Security', status: 'implemented', owner: 'Andriy Bondar', evidence: ['DC_Access_Logs.pdf', 'Environmental_Sensors.pdf'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Дата-центри з фізичним контролем доступу, відеоспостереженням, клімат-контролем, резервним живленням', source: 'ISO 27001 A.11.1-A.11.2', accessList: [{ email: 'a.bondar@novapay.ua', role: 'owner', name: 'Andriy Bondar', addedAt: '2025-01-01T10:00:00Z' }], lastReviewed: '2026-04-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z' },
  { id: genId(), title: 'A.12 Operations Security', description: 'Operational procedures, change management, capacity planning', framework: 'ISO 27001', category: 'Operations', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Change_Management_Procedure.pdf', 'Capacity_Report_Q2.xlsx'], evidenceLinks: ['https://novapay-jira/change-management'], attachments: [], controlDesign: 'NovaPay: ITIL-based change management в Jira Service Management, автоматизоване деплой через CI/CD, моніторинг потужностей', source: 'ISO 27001 A.12.1-A.12.7', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-03-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'A.13 Communications Security', description: 'Network security, segregation and information transfer', framework: 'ISO 27001', category: 'Network Security', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Network_Diagram_v3.pdf', 'Firewall_Rules.txt'], evidenceLinks: ['https://novapay-netops/network-diagram'], attachments: ['Network_Diagram_v3.pdf'], controlDesign: 'NovaPay: Мережева сегментація (prod/staging/dev), WAF, IDS/IPS, VPN для віддаленого доступу, ізоляція PCI CDE', source: 'ISO 27001 A.13.1-A.13.2', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-02-01T10:00:00Z' }, { email: 'i.petrenko@novapay.ua', role: 'reviewer', name: 'Ivan Petrenko', addedAt: '2025-02-10T10:00:00Z' }], lastReviewed: '2026-05-20', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-05-20T10:00:00Z' },
  { id: genId(), title: 'A.14 System Acquisition, Development & Maintenance', description: 'Security requirements, secure development, testing', framework: 'ISO 27001', category: 'SDLC', status: 'in_progress', owner: 'Dmytro Kovalenko', evidence: ['SDLC_Policy.pdf', 'Code_Review_Guidelines.docx'], evidenceLinks: ['https://novapay-github/security-pipeline'], attachments: [], controlDesign: 'NovaPay: SDLC з gate-перевірками, SAST/DAST у CI/CD, code review обов\'язковий, penetration testing щорічно', source: 'ISO 27001 A.14.1-A.14.3', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-04-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-04-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'A.15 Supplier Relationships', description: 'Third-party security, monitoring and reviews', framework: 'ISO 27001', category: 'TPRM', status: 'in_progress', owner: 'Andriy Bondar', evidence: ['Vendor_Risk_Assessment.xlsx', 'Supplier_Agreements.pdf'], evidenceLinks: ['https://novapay-vendor-portal'], attachments: [], controlDesign: 'NovaPay: Єдиний реєстр постачальників, оцінка ризиків перед підключенням, щорічний моніторинг, DORA compliance', source: 'ISO 27001 A.15.1-A.15.2', accessList: [{ email: 'a.bondar@novapay.ua', role: 'owner', name: 'Andriy Bondar', addedAt: '2025-05-01T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-05-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'A.16 Incident Management', description: 'Incident detection, response, reporting and lessons learned', framework: 'ISO 27001', category: 'Incident Response', status: 'in_progress', owner: 'Maria Koval', evidence: ['IRP_v0.9.docx'], evidenceLinks: ['https://novapay-siem/incidents'], attachments: ['IRP_v0.9.docx'], controlDesign: 'NovaPay: SIEM (Splunk), SOC (24/7), IRP документовано, incident response team визначена, щомісячні tabletops', source: 'ISO 27001 A.16.1', accessList: [{ email: 'm.koval@novapay.ua', role: 'owner', name: 'Maria Koval', addedAt: '2025-06-01T10:00:00Z' }, { email: 'd.kovalenko@novapay.ua', role: 'implementer', name: 'Dmytro Kovalenko', addedAt: '2025-06-05T10:00:00Z' }], lastReviewed: '2026-06-10', createdAt: '2025-06-01T10:00:00Z', updatedAt: '2026-06-10T10:00:00Z' },
  { id: genId(), title: 'A.17 Business Continuity', description: 'BCM, BCP, DRP and testing', framework: 'ISO 27001', category: 'BCM', status: 'pending', owner: 'Andriy Bondar', evidence: ['BCP_v1.0.pdf', 'BIA_Report.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: BIA проведено для критичних сервісів, BCP розробляється, DRP для основних систем, план тестування 2026 Q4', source: 'ISO 27001 A.17.1-A.17.2', accessList: [{ email: 'a.bondar@novapay.ua', role: 'owner', name: 'Andriy Bondar', addedAt: '2025-07-01T10:00:00Z' }], lastReviewed: '2026-03-01', createdAt: '2025-07-01T10:00:00Z', updatedAt: '2026-03-01T10:00:00Z' },
  { id: genId(), title: 'A.18 Compliance', description: 'Legal, regulatory and contractual compliance, IS reviews', framework: 'ISO 27001', category: 'Compliance', status: 'implemented', owner: 'Maria Koval', evidence: ['Compliance_Register.xlsx', 'Legal_Obligations.pdf'], evidenceLinks: ['https://novapay-compliance/register'], attachments: [], controlDesign: 'NovaPay: Реєстр регуляторних вимог, автоматизовані перевірки compliance, внутрішній аудит щорічно', source: 'ISO 27001 A.18.1-A.18.2', accessList: [{ email: 'm.koval@novapay.ua', role: 'owner', name: 'Maria Koval', addedAt: '2025-01-01T10:00:00Z' }, { email: 'o.shevchenko@novapay.ua', role: 'manager', name: 'Olena Shevchenko', addedAt: '2025-01-10T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },

  // === PCI DSS 4.0 Requirements (full sub-requirement expansion) ===
  { id: genId(), title: 'Req 1: Install & Maintain Network Security Controls', description: 'Install and maintain network security controls to protect cardholder data', framework: 'PCI DSS 4.0', category: 'Network Security', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['FW_Rules_Audit.txt', 'Network_Diagram_CDE.pdf'], evidenceLinks: ['https://novapay-netops/firewall-rules'], attachments: ['Network_Diagram_CDE.pdf'], controlDesign: 'NovaPay: CDE сегмент ізольований, Next-Gen FW, WAF, IDS/PS, щоквартальний перегляд правил', source: 'PCI DSS 4.0 Req 1', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-01-01T10:00:00Z' }], lastReviewed: '2026-05-15', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-05-15T10:00:00Z' },
  { id: genId(), title: 'Req 1.1: NSC Configuration & Maintenance', description: 'Network security controls (NSCs) are configured and maintained to protect the CDE', framework: 'PCI DSS 4.0', category: 'Network Security', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['NSC_Config_Guide.pdf', 'FW_Rule_Audit_Q2.xlsx'], evidenceLinks: ['https://novapay-netops/nsc-config'], attachments: [], controlDesign: 'NovaPay: NSCs (FW, WAF, IDS) налаштовані згідно vendor best practices, правило zero-trust, щоквартальний аудит конфігурацій', source: 'PCI DSS 4.0 Req 1.1', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-01-10T10:00:00Z' }], lastReviewed: '2026-05-10', createdAt: '2025-01-10T10:00:00Z', updatedAt: '2026-05-10T10:00:00Z' },
  { id: genId(), title: 'Req 1.2: CDE Network Access Restriction', description: 'Network access to and from the cardholder data environment is restricted', framework: 'PCI DSS 4.0', category: 'Network Security', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['CDE_Segmentation_Test.pdf', 'Access_Rules_Matrix.xlsx'], evidenceLinks: ['https://novapay-netops/cde-access-rules'], attachments: ['CDE_Segmentation_Test.pdf'], controlDesign: 'NovaPay: CDE сегмент ізольований ACL-правилами, DMZ для публічних сервісів, тільки необхідні порти відкриті', source: 'PCI DSS 4.0 Req 1.2', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-02-01T10:00:00Z' }, { email: 'i.petrenko@novapay.ua', role: 'reviewer', name: 'Ivan Petrenko', addedAt: '2025-02-10T10:00:00Z' }], lastReviewed: '2026-05-20', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-05-20T10:00:00Z' },
  { id: genId(), title: 'Req 1.3: Untrusted Network Connections Control', description: 'Network connections between trusted and untrusted networks are controlled', framework: 'PCI DSS 4.0', category: 'Network Security', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Connection_Diagram.pdf', 'VPN_Config.pdf'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: VPN з MFA для віддаленого доступу, TLS 1.3 для зовнішніх з\'єднань, автоматичне блокування неавторизованих спроб', source: 'PCI DSS 4.0 Req 1.3', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-02-15T10:00:00Z' }], lastReviewed: '2026-04-01', createdAt: '2025-02-15T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z' },
  { id: genId(), title: 'Req 1.4: Unmanaged Device Risk Controls', description: 'Risks to the CDE from computing devices not managed by the entity are addressed', framework: 'PCI DSS 4.0', category: 'Network Security', status: 'in_progress', owner: 'Dmytro Kovalenko', evidence: ['BYOD_Policy.pdf', 'Unmanaged_Device_Scan.pdf'], evidenceLinks: ['https://novapay-netops/byod-guidelines'], attachments: [], controlDesign: 'NovaPay: BYOD policy, NAC для неконтрольованих пристроїв, guest VLAN, обмежений доступ тільки через VPN + MFA', source: 'PCI DSS 4.0 Req 1.4', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-04-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-04-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 2: Apply Secure Configurations', description: 'Apply secure configurations to all system components', framework: 'PCI DSS 4.0', category: 'Configuration Management', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['CIS_Baselines.pdf', 'Config_Scan_Report.pdf'], evidenceLinks: ['https://novapay-cmdb/hardening'], attachments: [], controlDesign: 'NovaPay: CIS benchmarks для всіх систем, автоматизована перевірка конфігурацій, сканування щотижня', source: 'PCI DSS 4.0 Req 2', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-01-15T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-01-15T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 2.1: System Component Secure Management', description: 'System components are configured and managed securely', framework: 'PCI DSS 4.0', category: 'Configuration Management', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Hardening_Standards.pdf', 'Config_Compliance_Report.xlsx'], evidenceLinks: ['https://novapay-cmdb/hardening-standards'], attachments: [], controlDesign: 'NovaPay: Автоматизоване hardening через Ansible, стандарти CIS для Linux/Windows, видалення непотрібних сервісів і облікових записів', source: 'PCI DSS 4.0 Req 2.1', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-02-01T10:00:00Z' }], lastReviewed: '2026-05-15', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-05-15T10:00:00Z' },
  { id: genId(), title: 'Req 3: Protect Stored Account Data', description: 'Protect stored PAN, render it unreadable, implement retention policies', framework: 'PCI DSS 4.0', category: 'Data Protection', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['Encryption_Policy.pdf', 'Data_Retention_Schedule.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: PAN шифрується (AES-256), токенізація через vault, мінімізація зберігання, retention — 12 місяців', source: 'PCI DSS 4.0 Req 3', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-02-01T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Req 3.1: CHD Storage Minimisation', description: 'Storage of cardholder data is kept to a minimum', framework: 'PCI DSS 4.0', category: 'Data Protection', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['Data_Inventory_CHD.xlsx', 'Retention_Schedule_CHD.pdf'], evidenceLinks: ['https://novapay-data/chd-retention'], attachments: [], controlDesign: 'NovaPay: CHD data inventory, автоматичне видалення PAN після 12 місяців, щоквартальний аудит сховищ CHD', source: 'PCI DSS 4.0 Req 3.1', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-02-10T10:00:00Z' }, { email: 'o.shevchenko@novapay.ua', role: 'reviewer', name: 'Olena Shevchenko', addedAt: '2025-02-15T10:00:00Z' }], lastReviewed: '2026-05-10', createdAt: '2025-02-10T10:00:00Z', updatedAt: '2026-05-10T10:00:00Z' },
  { id: genId(), title: 'Req 3.2: SAD Not Stored After Authorisation', description: 'Sensitive authentication data (SAD) is not stored after authorisation', framework: 'PCI DSS 4.0', category: 'Data Protection', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['SAD_Storage_Audit.pdf', 'Payment_Flow_Diagram.pdf'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Перевірка коду — SAD не зберігається після авторизації, tokenization замість зберігання PAN, автоматичне очищення логів', source: 'PCI DSS 4.0 Req 3.2', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-03-01T10:00:00Z' }], lastReviewed: '2026-05-15', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-05-15T10:00:00Z' },
  { id: genId(), title: 'Req 3.3: PAN Rendered Unreadable at Rest', description: 'PAN is rendered unreadable anywhere it is stored', framework: 'PCI DSS 4.0', category: 'Cryptography', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Encryption_Implementation_Report.pdf', 'Key_Management_Procedures.docx'], evidenceLinks: ['https://novapay-wiki/security/pan-encryption'], attachments: [], controlDesign: 'NovaPay: AES-256 для PAN у сховищах, HSM для ключів, field-level encryption у БД, токенізація для API', source: 'PCI DSS 4.0 Req 3.3', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-03-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 3.4: PAN Formatting & Truncation', description: 'Formatting and truncation of PAN are documented and controlled', framework: 'PCI DSS 4.0', category: 'Data Protection', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['PAN_Display_Policy.pdf', 'Truncation_Config.pdf'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: PAN маскування (перші 6 + останні 4), truncation в логах, політика відображення PAN у додатках', source: 'PCI DSS 4.0 Req 3.4', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-03-15T10:00:00Z' }], lastReviewed: '2026-04-01', createdAt: '2025-03-15T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z' },
  { id: genId(), title: 'Req 3.5: PAN Secured with Cryptography', description: 'Primary account number (PAN) is secured with cryptography', framework: 'PCI DSS 4.0', category: 'Cryptography', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Crypto_Architecture.pdf', 'PAN_Encryption_Test.pdf'], evidenceLinks: ['https://novapay-wiki/security/crypto-details'], attachments: [], controlDesign: 'NovaPay: AES-256-GCM для PAN, key rotation, HSM integration, encryption at rest and in transit', source: 'PCI DSS 4.0 Req 3.5', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-04-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-04-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 3.6: Key Management for Stored Account Data', description: 'Keys used to encrypt stored account data are managed', framework: 'PCI DSS 4.0', category: 'Cryptography', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Key_Management_Policy.pdf', 'Key_Rotation_Log.xlsx'], evidenceLinks: ['https://novapay-hsm/key-management'], attachments: [], controlDesign: 'NovaPay: Key lifecycle management, HSM (Thales), ротація кожні 90 днів, split knowledge для master keys', source: 'PCI DSS 4.0 Req 3.6', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-04-01T10:00:00Z' }, { email: 'a.bondar@novapay.ua', role: 'approver', name: 'Andriy Bondar', addedAt: '2025-04-10T10:00:00Z' }], lastReviewed: '2026-05-20', createdAt: '2025-04-01T10:00:00Z', updatedAt: '2026-05-20T10:00:00Z' },
  { id: genId(), title: 'Req 4: Encrypt CHD in Transit', description: 'Strong cryptography for cardholder data transmission over open/public networks', framework: 'PCI DSS 4.0', category: 'Cryptography', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['TLS_Config.pdf', 'Certificate_Inventory.xlsx'], evidenceLinks: ['https://novapay-netops/tls-compliance'], attachments: [], controlDesign: 'NovaPay: TLS 1.3 тільки, HSTS, certificate pinning, автоматичне оновлення сертифікатів через cert-manager', source: 'PCI DSS 4.0 Req 4', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-02-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 4.1: PAN Protected with Strong Cryptography in Transit', description: 'PAN is protected with strong cryptography during transmission', framework: 'PCI DSS 4.0', category: 'Cryptography', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['TLS_Scan_Report_Q2.pdf', 'Cipher_Suite_Config.txt'], evidenceLinks: ['https://novapay-netops/tls-ciphers'], attachments: [], controlDesign: 'NovaPay: TLS 1.3 з strong cipher suites (AEAD), HSTS preload, certificate transparency, автоматичне блокування слабких шифрів', source: 'PCI DSS 4.0 Req 4.1', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-02-10T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-02-10T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 4.2: In-flight PAN Direct Public Access Protection', description: 'In-flight PANs are protected from direct public access', framework: 'PCI DSS 4.0', category: 'Cryptography', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['WAF_Rules_PCI.pdf', 'Public_Endpoint_Audit.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: WAF перед публічними endpoints, rate limiting, bot detection, block публічних запитів з PAN у відповідях', source: 'PCI DSS 4.0 Req 4.2', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-03-01T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Req 5: Protect Against Malware', description: 'Anti-malware protection for all systems, updated regularly', framework: 'PCI DSS 4.0', category: 'Endpoint Protection', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['AV_Deployment_Report.xlsx', 'Malware_Scan_Logs.pdf'], evidenceLinks: ['https://novapay-edr/endpoints'], attachments: [], controlDesign: 'NovaPay: EDR (CrowdStrike) на всіх endpoints, щоденне оновлення сигнатур, щотижневе сканування', source: 'PCI DSS 4.0 Req 5', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-01-01T10:00:00Z' }], lastReviewed: '2026-05-20', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-05-20T10:00:00Z' },
  { id: genId(), title: 'Req 5.1: Malware Detection & Prevention', description: 'Malicious software (malware) is prevented or detected', framework: 'PCI DSS 4.0', category: 'Endpoint Protection', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['EDR_Deployment_Status.xlsx', 'Malware_Block_Events_Q2.pdf'], evidenceLinks: ['https://novapay-edr/dashboard'], attachments: [], controlDesign: 'NovaPay: CrowdStrike Falcon EDR на всіх endpoints, real-time detection, автоматична ізоляція інфікованих хостів', source: 'PCI DSS 4.0 Req 5.1', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-01-10T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-01-10T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 5.2: Anti-malware Mechanisms Active & Monitored', description: 'Anti-malware mechanisms and processes are active, maintained, and monitored', framework: 'PCI DSS 4.0', category: 'Endpoint Protection', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['AV_Health_Report.pdf', 'EDR_Agent_Status.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Централізований моніторинг статусу EDR, alerting при відключенні агента, щотижневий звіт про покриття', source: 'PCI DSS 4.0 Req 5.2', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-02-01T10:00:00Z' }], lastReviewed: '2026-05-15', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-05-15T10:00:00Z' },
  { id: genId(), title: 'Req 5.3: Anti-phishing Mechanisms', description: 'Anti-phishing mechanisms protect users', framework: 'PCI DSS 4.0', category: 'Endpoint Protection', status: 'implemented', owner: 'Olena Shevchenko', evidence: ['Phishing_Simulation_Q2.pdf', 'Email_Security_Config.pdf'], evidenceLinks: ['https://novapay-security/phishing-awareness'], attachments: [], controlDesign: 'NovaPay: DMARC/DKIM/SPF, phishing-симуляції щомісяця, email filtering, user reporting button для фішингу', source: 'PCI DSS 4.0 Req 5.3', accessList: [{ email: 'o.shevchenko@novapay.ua', role: 'owner', name: 'Olena Shevchenko', addedAt: '2025-03-01T10:00:00Z' }, { email: 'd.kovalenko@novapay.ua', role: 'implementer', name: 'Dmytro Kovalenko', addedAt: '2025-03-05T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 6: Develop & Maintain Secure Systems', description: 'Develop and maintain secure systems and software, patch management', framework: 'PCI DSS 4.0', category: 'Patch Management', status: 'in_progress', owner: 'Dmytro Kovalenko', evidence: ['Patch_Policy.pdf', 'Patch_Status_Q2.xlsx'], evidenceLinks: ['https://novapay-jira/patch-mgmt'], attachments: [], controlDesign: 'NovaPay: Щомісячне патчування, critical CVEs — 48 годин, сканування вразливостей Qualys щотижня', source: 'PCI DSS 4.0 Req 6', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-03-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 6.1: Bespoke Software Developed Securely', description: 'Bespoke and custom software is developed securely', framework: 'PCI DSS 4.0', category: 'SDLC', status: 'in_progress', owner: 'Dmytro Kovalenko', evidence: ['Secure_Coding_Standards.pdf', 'Code_Review_Process.docx'], evidenceLinks: ['https://novapay-github/security-pipeline'], attachments: [], controlDesign: 'NovaPay: SAST (SonarQube) у CI/CD, code review обов\'язковий, security requirements в user stories', source: 'PCI DSS 4.0 Req 6.1', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-03-15T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-03-15T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 6.2: Vulnerability Identification & Remediation', description: 'Security vulnerabilities are identified and addressed', framework: 'PCI DSS 4.0', category: 'Patch Management', status: 'in_progress', owner: 'Dmytro Kovalenko', evidence: ['Vuln_Scan_Report_Q2.pdf', 'Remediation_Tracker.xlsx'], evidenceLinks: ['https://novapay-qualys/remediation'], attachments: [], controlDesign: 'NovaPay: Qualys VM, prioritization за CVSS v3, SLA: Critical 48h, High 7d, Medium 30d, звітність керівництву', source: 'PCI DSS 4.0 Req 6.2', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-03-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 6.3: Public-facing Web App Protection', description: 'Public-facing web applications are protected against attacks', framework: 'PCI DSS 4.0', category: 'Application Security', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['WAF_Rules_Review_Q2.pdf', 'DAST_Report_Q2.pdf'], evidenceLinks: ['https://novapay-waf/dashboard'], attachments: [], controlDesign: 'NovaPay: WAF (Cloudflare), DAST (Burp Suite) у CI/CD, щотижневе сканування OWASP Top 10', source: 'PCI DSS 4.0 Req 6.3', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-04-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-04-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 7: Restrict Access by Need-to-Know', description: 'Least privilege access to cardholder data', framework: 'PCI DSS 4.0', category: 'Access Control', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['Access_Matrix_CDE.xlsx', 'Need_to_Know_Policy.pdf'], evidenceLinks: ['https://novapay-idm/cde-access'], attachments: ['Access_Matrix_CDE.xlsx'], controlDesign: 'NovaPay: RBAC, обмеження доступу до CDE за принципом need-to-know, щоквартальний перегляд', source: 'PCI DSS 4.0 Req 7', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-01-01T10:00:00Z' }], lastReviewed: '2026-06-10', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-06-10T10:00:00Z' },
  { id: genId(), title: 'Req 7.1: Access Defined & Assigned by Need-to-Know', description: 'Access to systems and components is appropriately defined and assigned', framework: 'PCI DSS 4.0', category: 'Access Control', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['Role_Definitions_CDE.pdf', 'Access_Request_Process.docx'], evidenceLinks: ['https://novapay-idm/role-definitions'], attachments: [], controlDesign: 'NovaPay: Role mining для CDE, каталог ролей, процес запиту доступу, approval flow, JIT доступ для адмінів', source: 'PCI DSS 4.0 Req 7.1', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-01-10T10:00:00Z' }, { email: 'd.kovalenko@novapay.ua', role: 'implementer', name: 'Dmytro Kovalenko', addedAt: '2025-01-15T10:00:00Z' }], lastReviewed: '2026-05-15', createdAt: '2025-01-10T10:00:00Z', updatedAt: '2026-05-15T10:00:00Z' },
  { id: genId(), title: 'Req 7.2: User Access Management Based on Job Function', description: 'Access to systems is managed and limited based on the user\\\'s job function', framework: 'PCI DSS 4.0', category: 'Access Control', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['Access_Reviews_Q2.xlsx', 'SoD_Matrix.pdf'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: ABAC, role mining, segregation of duties (SoD), quarterly access certifications', source: 'PCI DSS 4.0 Req 7.2', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-02-01T10:00:00Z' }], lastReviewed: '2026-06-10', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-06-10T10:00:00Z' },
  { id: genId(), title: 'Req 8: Identify Users & Authenticate Access', description: 'Unique IDs, strong authentication, MFA for system components', framework: 'PCI DSS 4.0', category: 'Authentication', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['MFA_Report.pdf', 'Password_Policy_v1.5.pdf'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Azure AD + MFA, парольна політика (12+ символів), блокування після 5 спроб, PAM для привілейованого доступу', source: 'PCI DSS 4.0 Req 8', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-01-01T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Req 8.1: User Identity Verification & Access Authorisation', description: 'User identity is verified and access is authorised', framework: 'PCI DSS 4.0', category: 'Authentication', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['Identity_Verification_Process.pdf', 'Joiner_Mover_Leaver_Procedure.docx'], evidenceLinks: ['https://novapay-idm/jml-process'], attachments: [], controlDesign: 'NovaPay: JML process (Joiner-Mover-Leaver), identity verification при онбордингу, відкликання доступу при звільненні протягом 24 годин', source: 'PCI DSS 4.0 Req 8.1', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-01-15T10:00:00Z' }, { email: 'o.shevchenko@novapay.ua', role: 'approver', name: 'Olena Shevchenko', addedAt: '2025-01-20T10:00:00Z' }], lastReviewed: '2026-05-10', createdAt: '2025-01-15T10:00:00Z', updatedAt: '2026-05-10T10:00:00Z' },
  { id: genId(), title: 'Req 8.2: Strong Authentication Established', description: 'Strong authentication for users and administrators is established', framework: 'PCI DSS 4.0', category: 'Authentication', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['Password_Complexity_Config.pdf', 'Auth_Policy.pdf'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Мінімум 12 символів, complex паролі, блокування після 5 невдалих спроб, session timeout 15 хвилин', source: 'PCI DSS 4.0 Req 8.2', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-02-01T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Req 8.3: MFA Implemented', description: 'Multi-factor authentication (MFA) is implemented', framework: 'PCI DSS 4.0', category: 'Authentication', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['MFA_Deployment_Report.pdf', 'MFA_Coverage_Dashboard.xlsx'], evidenceLinks: ['https://novapay-idm/mfa-status'], attachments: [], controlDesign: 'NovaPay: MFA для всіх користувачів (Azure AD + Authenticator), FIDO2 keys для адмінів, push notifications', source: 'PCI DSS 4.0 Req 8.3', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-02-15T10:00:00Z' }, { email: 'd.kovalenko@novapay.ua', role: 'implementer', name: 'Dmytro Kovalenko', addedAt: '2025-02-20T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-02-15T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 8.4: User Identity & Auth Factor Management', description: 'Management of user identities and authentication factors is secure', framework: 'PCI DSS 4.0', category: 'Authentication', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['Identity_Management_Procedure.pdf', 'Auth_Factor_Audit.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Azure AD Identity Governance, access reviews, automated provisioning, auth factor inventory', source: 'PCI DSS 4.0 Req 8.4', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-03-01T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Req 8.5: Application & System Account Management', description: 'Use of application and system accounts and associated authentication factors is managed', framework: 'PCI DSS 4.0', category: 'Authentication', status: 'in_progress', owner: 'Ivan Petrenko', evidence: ['Service_Account_Inventory.xlsx', 'System_Account_Policy.pdf'], evidenceLinks: ['https://novapay-idm/service-accounts'], attachments: [], controlDesign: 'NovaPay: Service account registry, automatic password rotation, обмеження інтерактивного логіну, quarterly review', source: 'PCI DSS 4.0 Req 8.5', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-04-01T10:00:00Z' }, { email: 'd.kovalenko@novapay.ua', role: 'implementer', name: 'Dmytro Kovalenko', addedAt: '2025-04-05T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-04-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 9: Restrict Physical Access', description: 'Physical security for cardholder data and systems', framework: 'PCI DSS 4.0', category: 'Physical Security', status: 'implemented', owner: 'Andriy Bondar', evidence: ['DC_Access_Logs.pdf', 'Visitor_Register.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Біометричний доступ до дата-центру, CCTV, журнал відвідувачів, badge access system, escort policy', source: 'PCI DSS 4.0 Req 9', accessList: [{ email: 'a.bondar@novapay.ua', role: 'owner', name: 'Andriy Bondar', addedAt: '2025-01-01T10:00:00Z' }], lastReviewed: '2026-04-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z' },
  { id: genId(), title: 'Req 9.1: Physical Access Control Management', description: 'Physical access controls manage entry into facilities and sensitive areas', framework: 'PCI DSS 4.0', category: 'Physical Security', status: 'implemented', owner: 'Andriy Bondar', evidence: ['Physical_Access_Control_Policy.pdf', 'Facility_Access_Matrix.xlsx'], evidenceLinks: ['https://novapay-bcm/physical-access'], attachments: [], controlDesign: 'NovaPay: Багаторівнева система доступу (badge + biometry), anti-passback, escort policy для відвідувачів', source: 'PCI DSS 4.0 Req 9.1', accessList: [{ email: 'a.bondar@novapay.ua', role: 'owner', name: 'Andriy Bondar', addedAt: '2025-01-15T10:00:00Z' }], lastReviewed: '2026-04-01', createdAt: '2025-01-15T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z' },
  { id: genId(), title: 'Req 9.2: Physical Access Monitoring', description: 'Physical access is monitored', framework: 'PCI DSS 4.0', category: 'Physical Security', status: 'implemented', owner: 'Andriy Bondar', evidence: ['CCTV_System_Overview.pdf', 'Access_Log_Review_Process.docx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: CCTV з записом 90 днів, автоматичне сповіщення про несанкціонований доступ, щоденний перегляд логів', source: 'PCI DSS 4.0 Req 9.2', accessList: [{ email: 'a.bondar@novapay.ua', role: 'owner', name: 'Andriy Bondar', addedAt: '2025-02-01T10:00:00Z' }], lastReviewed: '2026-04-01', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z' },
  { id: genId(), title: 'Req 9.3: Media With CHD Secured', description: 'Media with cardholder data is secured, tracked, and destroyed', framework: 'PCI DSS 4.0', category: 'Physical Security', status: 'implemented', owner: 'Andriy Bondar', evidence: ['Media_Inventory.xlsx', 'Media_Destruction_Certificates.pdf'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Media tracking database, secure destruction (shredding/degaussing), inventory reconciliation щомісяця', source: 'PCI DSS 4.0 Req 9.3', accessList: [{ email: 'a.bondar@novapay.ua', role: 'owner', name: 'Andriy Bondar', addedAt: '2025-03-01T10:00:00Z' }], lastReviewed: '2026-04-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z' },
  { id: genId(), title: 'Req 9.4: POI Device Tamper Protection', description: 'POI devices are protected from tampering and substitution', framework: 'PCI DSS 4.0', category: 'Physical Security', status: 'implemented', owner: 'Andriy Bondar', evidence: ['POI_Device_Inventory.xlsx', 'Tamper_Inspections_Q2.pdf'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Inventory всіх POI пристроїв, щотижневі перевірки, anti-tamper seals, training для персоналу', source: 'PCI DSS 4.0 Req 9.4', accessList: [{ email: 'a.bondar@novapay.ua', role: 'owner', name: 'Andriy Bondar', addedAt: '2025-04-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-04-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 10: Log & Monitor All Access', description: 'Logging, monitoring, log review and retention for system components', framework: 'PCI DSS 4.0', category: 'Monitoring', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['SIEM_Architecture.pdf', 'Log_Review_Report.xlsx'], evidenceLinks: ['https://novapay-siem/dashboards'], attachments: [], controlDesign: 'NovaPay: Splunk SIEM, централізований збір логів, автоматичні алерти, щоденний перегляд, зберігання 12 місяців', source: 'PCI DSS 4.0 Req 10', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-02-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 10.1: Audit Log Implementation', description: 'Audit logs are implemented to capture all access to system components', framework: 'PCI DSS 4.0', category: 'Monitoring', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Log_Sources_Inventory.xlsx', 'Audit_Log_Fields_Definition.pdf'], evidenceLinks: ['https://novapay-siem/log-sources'], attachments: [], controlDesign: 'NovaPay: Centralized logging для всіх систем CDE, log source inventory, inclusion criteria for logging', source: 'PCI DSS 4.0 Req 10.1', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-02-15T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-02-15T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Req 10.2: Audit Log Protection', description: 'Audit logs are protected from destruction and unauthorised modifications', framework: 'PCI DSS 4.0', category: 'Monitoring', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Log_Protection_Controls.pdf', 'SIEM_Access_Control.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Write-once log storage, RBAC для SIEM, log integrity monitoring, alerts for log tampering', source: 'PCI DSS 4.0 Req 10.2', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-03-01T10:00:00Z' }, { email: 'i.petrenko@novapay.ua', role: 'approver', name: 'Ivan Petrenko', addedAt: '2025-03-05T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Req 10.3: Audit Log Review', description: 'Audit logs are reviewed to detect anomalies and suspicious activity', framework: 'PCI DSS 4.0', category: 'Monitoring', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Log_Review_Schedule.pdf', 'SIEM_Daily_Review_Report.pdf'], evidenceLinks: ['https://novapay-siem/review-dashboard'], attachments: [], controlDesign: 'NovaPay: Automated log review via SIEM, daily alerts review, weekly SOC analyst review, MTTR tracking', source: 'PCI DSS 4.0 Req 10.3', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-03-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 10.4: Audit Log Retention', description: 'Audit log history is retained and available for analysis', framework: 'PCI DSS 4.0', category: 'Monitoring', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Log_Retention_Policy.pdf', 'Retention_Compliance_Report.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: 12 місяців online, 24 місяці cold storage, automated purging, retention compliance monitoring', source: 'PCI DSS 4.0 Req 10.4', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-04-01T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-04-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Req 10.5: Time-Synchronisation Mechanisms', description: 'Time-synchronisation mechanisms support consistent time settings across systems', framework: 'PCI DSS 4.0', category: 'Monitoring', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['NTP_Architecture.pdf', 'Time_Sync_Audit.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: NTP stratum 2, all CDE systems sync to internal NTP, audit logging for time discrepancies', source: 'PCI DSS 4.0 Req 10.5', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-02-01T10:00:00Z' }], lastReviewed: '2026-04-01', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z' },
  { id: genId(), title: 'Req 10.6: Critical Security Control Failure Detection', description: 'Failures of critical security control systems are detected, reported, and responded to promptly', framework: 'PCI DSS 4.0', category: 'Monitoring', status: 'in_progress', owner: 'Dmytro Kovalenko', evidence: ['Security_Controls_Monitoring_Doc.pdf'], evidenceLinks: ['https://novapay-siem/control-health'], attachments: [], controlDesign: 'NovaPay: Health monitoring for security tools, automated alerting, escalation for failures, SLA for restoration', source: 'PCI DSS 4.0 Req 10.6', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-05-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-05-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 11: Test Security Regularly', description: 'Test security of systems and networks regularly', framework: 'PCI DSS 4.0', category: 'Security Testing', status: 'in_progress', owner: 'Dmytro Kovalenko', evidence: ['ASV_Scan_Q2.pdf', 'PT_Report_2026.pdf'], evidenceLinks: ['https://novapay-qualys/scans'], attachments: [], controlDesign: 'NovaPay: Qualys ASV сканування щоквартально, penetration testing щорічно, DAST/SAST у CI/CD, bug bounty', source: 'PCI DSS 4.0 Req 11', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-03-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 11.1: Wireless Access Point Monitoring', description: 'Wireless access points are identified and monitored', framework: 'PCI DSS 4.0', category: 'Security Testing', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['WAP_Scan_Report_Q2.pdf', 'Wireless_Inventory.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Quarterly wireless scans, rogue AP detection, WPA3 для всіх WAP, NAC для wireless клієнтів', source: 'PCI DSS 4.0 Req 11.1', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-04-01T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-04-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Req 11.2: Vulnerability Identification & Prioritisation', description: 'External and internal vulnerabilities are regularly identified, prioritised, and addressed', framework: 'PCI DSS 4.0', category: 'Security Testing', status: 'in_progress', owner: 'Dmytro Kovalenko', evidence: ['Vuln_Scan_External_Q2.pdf', 'Vuln_Scan_Internal_Q2.pdf'], evidenceLinks: ['https://novapay-qualys/vulnerabilities'], attachments: [], controlDesign: 'NovaPay: External ASV quarterly, internal scans weekly, risk-based prioritisation, SLA tracking', source: 'PCI DSS 4.0 Req 11.2', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-03-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 11.3: External & Internal Penetration Testing', description: 'External and internal penetration testing is performed', framework: 'PCI DSS 4.0', category: 'Security Testing', status: 'in_progress', owner: 'Dmytro Kovalenko', evidence: ['PT_Scope_2026.pdf', 'PT_Findings_Report_2025.pdf'], evidenceLinks: ['https://novapay-pentest/reports'], attachments: [], controlDesign: 'NovaPay: Annual penetration testing (external + internal), segmentation testing for CDE, remediation verification', source: 'PCI DSS 4.0 Req 11.3', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-06-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-06-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 11.4: Change Detection on Security-Critical Components', description: 'Detections of changes to security-critical components are managed', framework: 'PCI DSS 4.0', category: 'Security Testing', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['FIM_Config.pdf', 'Change_Alert_Report_Q2.pdf'], evidenceLinks: ['https://novapay-siem/fim-dashboard'], attachments: [], controlDesign: 'NovaPay: File Integrity Monitoring (Tripwire), critical file change alerts, automated change verification', source: 'PCI DSS 4.0 Req 11.4', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-04-01T10:00:00Z' }, { email: 'i.petrenko@novapay.ua', role: 'reviewer', name: 'Ivan Petrenko', addedAt: '2025-04-10T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-04-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Req 11.5: Unauthorised Payment Page Change Detection', description: 'Unauthorised changes on payment pages are detected and managed', framework: 'PCI DSS 4.0', category: 'Security Testing', status: 'pending', owner: 'Dmytro Kovalenko', evidence: [], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Payment page integrity checking, DOM monitoring, Content Security Policy, automatic alerting', source: 'PCI DSS 4.0 Req 11.5', accessList: [{ email: 'd.kovalenko@novapay.ua', role: 'owner', name: 'Dmytro Kovalenko', addedAt: '2025-07-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-07-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 12: Information Security Policies', description: 'Support information security with organisational policies and programs', framework: 'PCI DSS 4.0', category: 'Policies', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['PCI_Policy.pdf', 'Risk_Assessment_2026.pdf'], evidenceLinks: ['https://novapay-compliance/pci-policies'], attachments: [], controlDesign: 'NovaPay: Політики ІБ затверджені, щорічна оцінка ризиків, програма security awareness, план реагування на інциденти', source: 'PCI DSS 4.0 Req 12', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-01-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 12.1: Information Security Policy Management', description: 'Information security policy is established, published, maintained, and disseminated', framework: 'PCI DSS 4.0', category: 'Policies', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['IS_Policy_v2.3.pdf', 'Policy_Acceptance_Records.xlsx'], evidenceLinks: ['https://novapay-confluence/policy/is-policy'], attachments: [], controlDesign: 'NovaPay: Central policy repository in Confluence, annual review cycle, mandatory acceptance, version control', source: 'PCI DSS 4.0 Req 12.1', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-01-10T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-01-10T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Req 12.2: Risk Management Integration', description: 'Risk management is integrated into business activities', framework: 'PCI DSS 4.0', category: 'Risk Management', status: 'implemented', owner: 'Maria Koval', evidence: ['Enterprise_Risk_Register.xlsx', 'Risk_Appetite_Statement.pdf'], evidenceLinks: ['https://novapay-erm/risks'], attachments: [], controlDesign: 'NovaPay: Integrated risk management framework, risk appetite approved by board, quarterly risk reviews', source: 'PCI DSS 4.0 Req 12.2', accessList: [{ email: 'm.koval@novapay.ua', role: 'owner', name: 'Maria Koval', addedAt: '2025-02-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 12.3: PCI DSS Compliance Management', description: 'PCI DSS compliance is managed', framework: 'PCI DSS 4.0', category: 'Compliance', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['PCI_Compliance_Program.pdf', 'SAQ_D_Progress.xlsx'], evidenceLinks: ['https://novapay-compliance/pci-program'], attachments: [], controlDesign: 'NovaPay: Dedicated PCI program, compliance calendar, evidence collection, quarterly progress reviews', source: 'PCI DSS 4.0 Req 12.3', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-01-01T10:00:00Z' }, { email: 'm.koval@novapay.ua', role: 'reviewer', name: 'Maria Koval', addedAt: '2025-01-15T10:00:00Z' }], lastReviewed: '2026-06-10', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-06-10T10:00:00Z' },
  { id: genId(), title: 'Req 12.4: Operational Security Responsibilities', description: 'Operational security responsibilities are assigned', framework: 'PCI DSS 4.0', category: 'Governance', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['RACI_Matrix_PCI.xlsx', 'Security_Roles_Descriptions.pdf'], evidenceLinks: ['https://novapay-wiki/organization/security-roles'], attachments: [], controlDesign: 'NovaPay: RACI matrix for PCI, assigned owners for each requirement, backup for key roles', source: 'PCI DSS 4.0 Req 12.4', accessList: [{ email: 'i.petrenko@novapay.ua', role: 'owner', name: 'Ivan Petrenko', addedAt: '2025-03-01T10:00:00Z' }, { email: 'a.bondar@novapay.ua', role: 'viewer', name: 'Andriy Bondar', addedAt: '2025-03-10T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Req 12.5: Security Awareness Education', description: 'Security awareness education is an ongoing activity', framework: 'PCI DSS 4.0', category: 'Awareness', status: 'implemented', owner: 'Olena Shevchenko', evidence: ['Awareness_Training_Material.pdf', 'Training_Completion_Report.xlsx'], evidenceLinks: ['https://novapay-train/security'], attachments: [], controlDesign: 'NovaPay: Annual mandatory training, monthly phishing simulations, PCI-specific awareness module, metrics tracking', source: 'PCI DSS 4.0 Req 12.5', accessList: [{ email: 'o.shevchenko@novapay.ua', role: 'owner', name: 'Olena Shevchenko', addedAt: '2025-01-01T10:00:00Z' }, { email: 'i.petrenko@novapay.ua', role: 'approver', name: 'Ivan Petrenko', addedAt: '2025-01-10T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 12.6: Personnel Screening', description: 'Personnel are screened to reduce risks', framework: 'PCI DSS 4.0', category: 'HR', status: 'implemented', owner: 'Olena Shevchenko', evidence: ['Background_Check_Policy.pdf', 'Screening_Records.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Background checks for all personnel with CDE access, 3-year re-screening, criminal records check', source: 'PCI DSS 4.0 Req 12.6', accessList: [{ email: 'o.shevchenko@novapay.ua', role: 'owner', name: 'Olena Shevchenko', addedAt: '2025-04-01T10:00:00Z' }], lastReviewed: '2026-05-01', createdAt: '2025-04-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Req 12.7: Service Provider Risk Management', description: 'Risk to CDE from service providers is managed', framework: 'PCI DSS 4.0', category: 'TPRM', status: 'in_progress', owner: 'Andriy Bondar', evidence: ['Service_Provider_Register.xlsx', 'SP_Risk_Assessments.pdf'], evidenceLinks: ['https://novapay-vendor-portal/pci'], attachments: [], controlDesign: 'NovaPay: Service provider inventory, due diligence before engagement, annual risk assessments, PCI DSS compliance verification', source: 'PCI DSS 4.0 Req 12.7', accessList: [{ email: 'a.bondar@novapay.ua', role: 'owner', name: 'Andriy Bondar', addedAt: '2025-05-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-05-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 12.8: Service Provider PCI DSS Confirmation', description: 'Service providers confirm they support customers\\\' PCI DSS compliance', framework: 'PCI DSS 4.0', category: 'TPRM', status: 'in_progress', owner: 'Andriy Bondar', evidence: ['SP_Compliance_Attestations.pdf', 'SP_Compliance_Status.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: AOC collection from service providers, annual compliance confirmation, inventory of in-scope TPSPs', source: 'PCI DSS 4.0 Req 12.8', accessList: [{ email: 'a.bondar@novapay.ua', role: 'owner', name: 'Andriy Bondar', addedAt: '2025-06-01T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-06-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Req 12.9: Emergency Procedures Management', description: 'Security and application of emergency procedures is managed', framework: 'PCI DSS 4.0', category: 'BCM', status: 'in_progress', owner: 'Andriy Bondar', evidence: ['Emergency_Procedures.pdf', 'Emergency_Test_Report.pdf'], evidenceLinks: ['https://novapay-bcm/emergency-procedures'], attachments: [], controlDesign: 'NovaPay: Emergency contact list, crisis communication plan, emergency testing annually, incident classification', source: 'PCI DSS 4.0 Req 12.9', accessList: [{ email: 'a.bondar@novapay.ua', role: 'owner', name: 'Andriy Bondar', addedAt: '2025-06-01T10:00:00Z' }, { email: 'm.koval@novapay.ua', role: 'reviewer', name: 'Maria Koval', addedAt: '2025-06-15T10:00:00Z' }], lastReviewed: '2026-06-01', createdAt: '2025-06-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },

  // === GDPR Controls ===
  { id: genId(), title: 'Data Processing Register (RoPA)', description: 'Register of personal data processing operations', framework: 'GDPR', category: 'Privacy', status: 'implemented', owner: 'Olena Shevchenko', evidence: ['RoPA.xlsx', 'Data_Inventory.pdf'], evidenceLinks: ['https://novapay-privacy/ropa'], attachments: ['RoPA_v2.xlsx'], controlDesign: 'NovaPay: Реєстр операцій обробки ПД, Data mapping, автоматизоване оновлення, відповідальний DPO', source: 'GDPR Art. 30', accessList: [], lastReviewed: '2026-05-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'DPIA Process', description: 'Data Protection Impact Assessment for high-risk processing', framework: 'GDPR', category: 'Privacy', status: 'implemented', owner: 'Olena Shevchenko', evidence: ['DPIA_Template.docx', 'DPIA_CRM_2026.pdf'], evidenceLinks: ['https://novapay-confluence/dpia'], attachments: [], controlDesign: 'NovaPay: DPIA для всіх нових систем з обробкою ПД, затвердження DPO, щорічний перегляд', source: 'GDPR Art. 35', accessList: [], lastReviewed: '2026-06-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Data Subject Rights Management', description: 'Process for handling DSARs (access, rectification, erasure, portability)', framework: 'GDPR', category: 'Privacy Rights', status: 'implemented', owner: 'Olena Shevchenko', evidence: ['DSAR_Procedure.pdf', 'DSAR_Log_2026.xlsx'], evidenceLinks: ['https://novapay-privacy/dsar-portal'], attachments: [], controlDesign: 'NovaPay: Портал для запитів суб\'єктів даних, SLA 30 днів, автоматизована обробка, логування всіх запитів', source: 'GDPR Art. 15-20', accessList: [], lastReviewed: '2026-05-15', createdAt: '2025-04-01T10:00:00Z', updatedAt: '2026-05-15T10:00:00Z' },
  { id: genId(), title: 'Consent Management', description: 'Obtain, record and manage consent for processing', framework: 'GDPR', category: 'Privacy Rights', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['Consent_Form.pdf', 'Consent_Records.xlsx'], evidenceLinks: ['https://novapay-cookie/consent'], attachments: [], controlDesign: 'NovaPay: Cookie consent banner, granular consent, preference center, audit trail for consent changes', source: 'GDPR Art. 7', accessList: [], lastReviewed: '2026-04-01', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z' },
  { id: genId(), title: 'Data Breach Notification', description: 'Process to detect, report and notify data breaches', framework: 'GDPR', category: 'Incident Response', status: 'in_progress', owner: 'Maria Koval', evidence: ['Breach_Notification_Procedure.docx'], evidenceLinks: ['https://novapay-siem/breach-playbook'], attachments: [], controlDesign: 'NovaPay: Процедура повідомлення про порушення, 72 години для DPA, форма для реєстрації інцидентів', source: 'GDPR Art. 33-34', accessList: [], lastReviewed: '2026-06-01', createdAt: '2025-05-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Data Protection Officer (DPO)', description: 'DPO appointment, responsibilities and independence', framework: 'GDPR', category: 'Governance', status: 'implemented', owner: 'Olena Shevchenko', evidence: ['DPO_Appointment.pdf', 'DPO_Contact.pdf'], evidenceLinks: ['https://novapay-privacy/dpo'], attachments: [], controlDesign: 'NovaPay: DPO призначено, зареєстровано в НБУ, незалежність, звітність наглядовій раді', source: 'GDPR Art. 37-39', accessList: [], lastReviewed: '2026-01-15', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-01-15T10:00:00Z' },
  { id: genId(), title: 'Privacy by Design & Default', description: 'Data protection integrated into processing activities and systems', framework: 'GDPR', category: 'SDLC', status: 'in_progress', owner: 'Dmytro Kovalenko', evidence: ['PbD_Checklist.docx'], evidenceLinks: ['https://novapay-wiki/sdlc/privacy'], attachments: [], controlDesign: 'NovaPay: PbD review у SDLC, data minimization, pseudonymization, privacy review перед релізом', source: 'GDPR Art. 25', accessList: [], lastReviewed: '2026-05-01', createdAt: '2025-06-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'International Data Transfers', description: 'Safeguards for transferring personal data outside EEA', framework: 'GDPR', category: 'Data Governance', status: 'pending', owner: 'Olena Shevchenko', evidence: ['TIA_Report.pdf', 'SCCs_Agreements.pdf'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Transfer Impact Assessments, SCC в договорах, перелік третіх країн, DPA monitoring', source: 'GDPR Art. 44-49', accessList: [], lastReviewed: '2026-03-01', createdAt: '2025-07-01T10:00:00Z', updatedAt: '2026-03-01T10:00:00Z' },

  // === NBU Resolution №143 (BCM) Controls ===
  { id: genId(), title: 'Business Impact Analysis (BIA)', description: 'Identify critical functions, dependencies, RTO/RPO', framework: 'NBU Resolution №143', category: 'BIA', status: 'in_progress', owner: 'Andriy Bondar', evidence: ['BIA_Report_2026.xlsx', 'Critical_Functions.pdf'], evidenceLinks: ['https://novapay-bcm/bia'], attachments: ['BIA_Report_2026.xlsx'], controlDesign: 'NovaPay: BIA для всіх критичних функцій, визначення RTO/RPO, залежності сервісів, щорічне оновлення', source: 'НБУ №143 ст. 5', accessList: [], lastReviewed: '2026-06-01', createdAt: '2025-06-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Business Continuity Strategy', description: 'Selected BCM strategies for critical functions', framework: 'NBU Resolution №143', category: 'BCP', status: 'pending', owner: 'Andriy Bondar', evidence: ['BC_Strategy.docx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Альтернативні стратегії (redundancy, failover, cloud DR), економічне обґрунтування', source: 'НБУ №143 ст. 6', accessList: [], lastReviewed: '2026-04-01', createdAt: '2025-07-01T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z' },
  { id: genId(), title: 'Business Continuity Plans (BCP)', description: 'Documented plans for maintaining critical operations', framework: 'NBU Resolution №143', category: 'BCP', status: 'pending', owner: 'Andriy Bondar', evidence: ['BCP_v1.0.docx'], evidenceLinks: ['https://novapay-confluence/bcp'], attachments: [], controlDesign: 'NovaPay: BCP для критичних функцій, процедури відновлення, контакти, RACI, план комунікації', source: 'НБУ №143 ст. 7', accessList: [], lastReviewed: '2026-03-01', createdAt: '2025-08-01T10:00:00Z', updatedAt: '2026-03-01T10:00:00Z' },
  { id: genId(), title: 'RTO/RPO Definition & Tracking', description: 'Recovery Time Objective and Recovery Point Objective for critical services', framework: 'NBU Resolution №143', category: 'BCP', status: 'in_progress', owner: 'Andriy Bondar', evidence: ['RTO_RPO_Matrix.xlsx'], evidenceLinks: ['https://novapay-bcm/rto-rpo'], attachments: [], controlDesign: 'NovaPay: RTO ≤ 4 години для критичних систем, RPO ≤ 15 хвилин, моніторинг виконання SLA', source: 'НБУ №143 ст. 8', accessList: [], lastReviewed: '2026-05-01', createdAt: '2025-08-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Incident Response & Crisis Management', description: 'Incident detection, escalation, crisis communication', framework: 'NBU Resolution №143', category: 'Incident Response', status: 'in_progress', owner: 'Maria Koval', evidence: ['Crisis_Management_Plan.docx', 'Escalation_Matrix.pdf'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Crisis management team, escalation procedure, комунікаційний план для НБУ, кризовий центр', source: 'НБУ №143 ст. 9', accessList: [], lastReviewed: '2026-06-01', createdAt: '2025-09-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'BCP Testing & Exercises', description: 'Regular testing of BCP and DR plans', framework: 'NBU Resolution №143', category: 'Testing', status: 'pending', owner: 'Andriy Bondar', evidence: ['Test_Plan_2026.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Щорічне тестування BCP, щоквартальні tabletop exercises, DR test для критичних систем, звіт для НБУ', source: 'НБУ №143 ст. 10', accessList: [], lastReviewed: '2026-02-01', createdAt: '2025-10-01T10:00:00Z', updatedAt: '2026-02-01T10:00:00Z' },
  { id: genId(), title: 'BCM Governance & Reporting', description: 'BCM framework governance, roles, reporting to board', framework: 'NBU Resolution №143', category: 'Governance', status: 'implemented', owner: 'Andriy Bondar', evidence: ['BCM_Charter.pdf', 'BCM_Report_Board_Q2.pdf'], evidenceLinks: ['https://novapay-bcm/governance'], attachments: [], controlDesign: 'NovaPay: BCM framework затверджений, звітність правлінню щоквартально, BCM комітет', source: 'НБУ №143 ст. 4', accessList: [], lastReviewed: '2026-06-01', createdAt: '2025-05-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Dependency Mapping & Third-Party BCP', description: 'Critical third-party dependencies and their BCP readiness', framework: 'NBU Resolution №143', category: 'TPRM', status: 'pending', owner: 'Andriy Bondar', evidence: ['Vendor_Dependency_Map.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Мапа залежностей від постачальників, оцінка BCP readiness постачальників, резервування', source: 'НБУ №143 ст. 11', accessList: [], lastReviewed: '2026-03-01', createdAt: '2025-11-01T10:00:00Z', updatedAt: '2026-03-01T10:00:00Z' },

  // === NBU Resolution №95 (Information Security) Controls ===
  { id: genId(), title: 'Information Security Policy Framework', description: 'IS policies, procedures and governance for banking systems', framework: 'NBU Resolution №95', category: 'Policies', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['IS_Policy_NBU95.pdf', 'Policy_Registry.xlsx'], evidenceLinks: ['https://novapay-confluence/isp'], attachments: ['IS_Policy_NBU95.pdf'], controlDesign: 'NovaPay: Комплексна політика ІБ банку, затверджена правлінням, щорічний перегляд, відповідність НБУ №95', source: 'НБУ №95 ст. 3', accessList: [], lastReviewed: '2026-06-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Asset Management & Classification', description: 'Identification, classification and inventory of information assets', framework: 'NBU Resolution №95', category: 'Asset Management', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Asset_Register_NBU.xlsx', 'Classification_Policy.pdf'], evidenceLinks: ['https://novapay-cmdb/nbu-assets'], attachments: [], controlDesign: 'NovaPay: Реєстр інформаційних активів, 3 рівні класифікації, власники активів, оцінка критичності', source: 'НБУ №95 ст. 4', accessList: [], lastReviewed: '2026-05-01', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Information Risk Management', description: 'Risk assessment, treatment and monitoring for banking IS risks', framework: 'NBU Resolution №95', category: 'Risk Management', status: 'in_progress', owner: 'Maria Koval', evidence: ['Risk_Register_NBU.xlsx', 'Risk_Assessment_Report.pdf'], evidenceLinks: ['https://novapay-erm/risks'], attachments: [], controlDesign: 'NovaPay: Скоринг ризиків (inherent/residual), risk appetite, плани обробки, звітність для НБУ', source: 'НБУ №95 ст. 5', accessList: [], lastReviewed: '2026-06-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Access Control & Authentication', description: 'User access management, privileged access, authentication controls', framework: 'NBU Resolution №95', category: 'Access Control', status: 'implemented', owner: 'Ivan Petrenko', evidence: ['Access_Policy_NBU.pdf', 'Privileged_Access_Review.xlsx'], evidenceLinks: ['https://novapay-idm/pam'], attachments: [], controlDesign: 'NovaPay: PAM для привілейованого доступу, MFA, SSO, сегрегація обов\'язків, щомісячний перегляд', source: 'НБУ №95 ст. 6', accessList: [], lastReviewed: '2026-06-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Cryptographic Protection', description: 'Encryption, key management and digital signatures', framework: 'NBU Resolution №95', category: 'Cryptography', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Crypto_Policy_NBU.pdf', 'Key_Inventory.xlsx'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Кваліфіковані ЕЦП, AES-256, TLS 1.3, HSM, управління ключами згідно з вимогами НБУ', source: 'НБУ №95 ст. 7', accessList: [], lastReviewed: '2026-05-15', createdAt: '2025-02-01T10:00:00Z', updatedAt: '2026-05-15T10:00:00Z' },
  { id: genId(), title: 'Physical & Environmental Security', description: 'Physical protection of banking information assets', framework: 'NBU Resolution №95', category: 'Physical Security', status: 'implemented', owner: 'Andriy Bondar', evidence: ['DC_Security_Report.pdf', 'Physical_Access_Policy.pdf'], evidenceLinks: [], attachments: [], controlDesign: 'NovaPay: Багаторівневий фізичний доступ, CCTV, біометрія, охорона 24/7, резервне живлення', source: 'НБУ №95 ст. 8', accessList: [], lastReviewed: '2026-04-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z' },
  { id: genId(), title: 'Network Security & Segmentation', description: 'Network security controls for banking infrastructure', framework: 'NBU Resolution №95', category: 'Network Security', status: 'implemented', owner: 'Dmytro Kovalenko', evidence: ['Network_Architecture_NBU.pdf', 'Segmentation_Rules.xlsx'], evidenceLinks: ['https://novapay-netops/nbu-network'], attachments: [], controlDesign: 'NovaPay: Сегментація мережі, DMZ, IDS/IPS, WAF, DDoS захист, ізоляція АБС', source: 'НБУ №95 ст. 9', accessList: [], lastReviewed: '2026-05-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Incident & Event Management', description: 'Security incident detection, response and reporting to NBU', framework: 'NBU Resolution №95', category: 'Incident Response', status: 'in_progress', owner: 'Maria Koval', evidence: ['Incident_Procedure_NBU.docx', 'SIEM_Alerts_Report.xlsx'], evidenceLinks: ['https://novapay-siem/nbu-incidents'], attachments: [], controlDesign: 'NovaPay: SOC 24/7, SIEM, автоматичне сповіщення НБУ, реєстр інцидентів, lessons learned', source: 'НБУ №95 ст. 10', accessList: [], lastReviewed: '2026-06-01', createdAt: '2025-04-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Vulnerability Management', description: 'Identification, assessment and remediation of vulnerabilities', framework: 'NBU Resolution №95', category: 'Security Testing', status: 'in_progress', owner: 'Dmytro Kovalenko', evidence: ['Vulnerability_Scan_Q2.pdf', 'Remediation_Plan.xlsx'], evidenceLinks: ['https://novapay-qualys/dashboard'], attachments: [], controlDesign: 'NovaPay: Qualys, щотижневе сканування, prioritization за CVSS, SLA на виправлення, звітність НБУ', source: 'НБУ №95 ст. 11', accessList: [], lastReviewed: '2026-06-01', createdAt: '2025-03-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Third-Party & Outsourcing Security', description: 'Security controls for third-party services and outsourcing', framework: 'NBU Resolution №95', category: 'TPRM', status: 'in_progress', owner: 'Andriy Bondar', evidence: ['Vendor_Security_Assessment.xlsx', 'Outsourcing_Register.pdf'], evidenceLinks: ['https://novapay-vendor-portal/nbu'], attachments: [], controlDesign: 'NovaPay: Оцінка безпеки постачальників, договори з clauses ІБ, моніторинг third-party ризиків', source: 'НБУ №95 ст. 12', accessList: [], lastReviewed: '2026-05-01', createdAt: '2025-05-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Regulatory Compliance & Audit', description: 'Compliance with NBU requirements and internal/external audit', framework: 'NBU Resolution №95', category: 'Compliance', status: 'implemented', owner: 'Maria Koval', evidence: ['NBU_Compliance_Register.xlsx', 'Audit_Report_2025.pdf'], evidenceLinks: ['https://novapay-compliance/nbu95'], attachments: [], controlDesign: 'NovaPay: Реєстр відповідності НБУ №95, внутрішній аудит, звітність наглядовій раді', source: 'НБУ №95 ст. 13', accessList: [], lastReviewed: '2026-06-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Security Awareness & Training', description: 'Ongoing security training and awareness program', framework: 'NBU Resolution №95', category: 'Awareness', status: 'implemented', owner: 'Olena Shevchenko', evidence: ['Training_Program.pdf', 'Awareness_Metrics.xlsx'], evidenceLinks: ['https://novapay-train/security'], attachments: [], controlDesign: 'NovaPay: Обов\'язкове навчання, фішинг-симуляції, щомісячні новини, тестування знань', source: 'НБУ №95 ст. 14', accessList: [], lastReviewed: '2026-06-01', createdAt: '2025-01-15T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
];

const SEED_POLICIES: Policy[] = [
  { id: genId(), title: 'Information Security Policy', version: '2.3', status: 'published', framework: 'ISO 27001', owner: 'Ivan Petrenko', description: 'Overall ISMS policy', lastReviewed: '2026-05-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Data Protection Policy', version: '1.2', status: 'published', framework: 'GDPR', owner: 'Olena Shevchenko', description: 'Personal data processing and protection', lastReviewed: '2026-04-15', createdAt: '2025-06-01T10:00:00Z', updatedAt: '2026-04-15T10:00:00Z' },
  { id: genId(), title: 'Incident Response Policy', version: '0.9', status: 'in_review', framework: 'NIST CSF', owner: 'Maria Koval', description: 'Incident handling and escalation', lastReviewed: '2026-06-10', createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-06-10T10:00:00Z' },
  { id: genId(), title: 'Third-Party Risk Policy', version: '0.5', status: 'draft', framework: 'DORA', owner: 'Andriy Bondar', description: 'Vendor risk management framework', lastReviewed: '2026-06-01', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-06-01T10:00:00Z' },
  { id: genId(), title: 'Acceptable Use Policy', version: '3.0', status: 'published', framework: 'ISO 27001', owner: 'Ivan Petrenko', description: 'Acceptable use of company assets', lastReviewed: '2026-03-01', createdAt: '2024-01-01T10:00:00Z', updatedAt: '2026-03-01T10:00:00Z' },
  { id: genId(), title: 'Business Continuity Policy', version: '1.0', status: 'published', framework: 'NBU Resolution №143', owner: 'Andriy Bondar', description: 'BCM framework', lastReviewed: '2026-02-01', createdAt: '2025-12-01T10:00:00Z', updatedAt: '2026-02-01T10:00:00Z' },
  { id: genId(), title: 'Password Policy', version: '1.5', status: 'published', framework: 'ISO 27001', owner: 'Ivan Petrenko', description: 'Password requirements and management', lastReviewed: '2026-04-01', createdAt: '2025-01-01T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z' },
  { id: genId(), title: 'Cloud Security Policy', version: '0.8', status: 'in_review', framework: 'SOC 2', owner: 'Dmytro Kovalenko', description: 'Cloud service security requirements', lastReviewed: '2026-05-20', createdAt: '2026-03-01T10:00:00Z', updatedAt: '2026-05-20T10:00:00Z' },
];

const SEED_CHECKS: AutomatedCheck[] = [
  { id: genId(), name: 'MFA enabled on all admin accounts', status: 'passed', framework: 'ISO 27001', lastRun: '2026-07-02T06:00:00Z', details: 'All 24 admin accounts have MFA enabled' },
  { id: genId(), name: 'S3 bucket public access blocked', status: 'passed', framework: 'SOC 2', lastRun: '2026-07-02T06:00:00Z', details: 'All 156 S3 buckets are properly restricted' },
  { id: genId(), name: 'Encryption at rest - RDS', status: 'passed', framework: 'PCI DSS', lastRun: '2026-07-02T06:00:00Z', details: 'All 12 RDS instances encrypted' },
  { id: genId(), name: 'SSL/TLS certificate expiry', status: 'failed', framework: 'NIST CSF', lastRun: '2026-07-02T06:00:00Z', details: '3 certificates expiring within 30 days' },
  { id: genId(), name: 'Unpatched critical CVEs', status: 'failed', framework: 'ISO 27001', lastRun: '2026-07-02T06:00:00Z', details: '15 critical vulnerabilities unpatched in production' },
  { id: genId(), name: 'IAM unused roles cleanup', status: 'passed', framework: 'SOC 2', lastRun: '2026-07-01T06:00:00Z', details: 'All unused IAM roles removed' },
  { id: genId(), name: 'CloudTrail enabled in all regions', status: 'failed', framework: 'PCI DSS', lastRun: '2026-07-02T06:00:00Z', details: '2 regions missing CloudTrail logging' },
  { id: genId(), name: 'Data retention compliance', status: 'passed', framework: 'GDPR', lastRun: '2026-07-01T06:00:00Z', details: 'Data retention policies applied correctly' },
  { id: genId(), name: 'Network segmentation validation', status: 'failed', framework: 'PCI DSS', lastRun: '2026-07-02T06:00:00Z', details: 'CDE network segmentation rule missing in 1 subnet' },
  { id: genId(), name: 'Backup verification - critical systems', status: 'failed', framework: 'NBU Resolution №143', lastRun: '2026-07-02T06:00:00Z', details: '4 critical systems have no verified backup in 7 days' },
  { id: genId(), name: 'Anti-malware endpoint coverage', status: 'passed', framework: 'ISO 27001', lastRun: '2026-07-02T06:00:00Z', details: '98% of endpoints have active anti-malware' },
  { id: genId(), name: 'Access review - privileged accounts', status: 'failed', framework: 'NIST CSF', lastRun: '2026-07-01T06:00:00Z', details: '8 privileged accounts not reviewed in 90 days' },
  { id: genId(), name: 'WAF ruleset update', status: 'error', framework: 'PCI DSS', lastRun: '2026-07-01T06:00:00Z', details: 'WAF agent unreachable - check failed' },
  { id: genId(), name: 'Container image vulnerability scan', status: 'passed', framework: 'SOC 2', lastRun: '2026-07-02T06:00:00Z', details: 'All container images scanned, no critical issues' },
  { id: genId(), name: 'GDPR data subject request process', status: 'failed', framework: 'GDPR', lastRun: '2026-07-01T06:00:00Z', details: 'DSAR response time exceeded 30-day SLA in 2 cases' },
];

const SEED_MILESTONES: Milestone[] = [
  { id: genId(), title: 'Phase 1: Gap Assessment', description: 'Complete gap analysis against all regulatory frameworks', dueDate: '2026-08-01', status: 'in_progress', framework: 'All', progress: 65 },
  { id: genId(), title: 'Phase 2: Policy Implementation', description: 'Develop and publish all required policies', dueDate: '2026-10-01', status: 'not_started', framework: 'All', progress: 0 },
  { id: genId(), title: 'Phase 3: Control Implementation', description: 'Implement technical and administrative controls', dueDate: '2026-12-01', status: 'not_started', framework: 'All', progress: 0 },
  { id: genId(), title: 'Phase 4: Internal Audit', description: 'Conduct internal audit before external certification', dueDate: '2027-02-01', status: 'not_started', framework: 'All', progress: 0 },
  { id: genId(), title: 'ISO 27001 Certification', description: 'Achieve ISO 27001:2022 certification', dueDate: '2027-03-01', status: 'not_started', framework: 'ISO 27001', progress: 35 },
  { id: genId(), title: 'PCI DSS Compliance', description: 'Complete PCI DSS 4.0 compliance validation', dueDate: '2027-01-01', status: 'not_started', framework: 'PCI DSS', progress: 15 },
];

const SEED_DOCUMENTS: GRCDocument[] = [
  { id: genId(), title: 'Information Security Policy v2.3', type: 'policy', framework: 'ISO 27001', status: 'active', files: [{ name: 'IS_Policy_v2.3.pdf', size: 245760, type: 'application/pdf' }], links: ['https://novapay-confluence/policy/is-policy'], uploadedAt: '2026-05-01T10:00:00Z', updatedAt: '2026-05-01T10:00:00Z' },
  { id: genId(), title: 'Risk Assessment Report 2026', type: 'report', framework: 'ISO 27001', status: 'active', files: [{ name: 'Risk_Assessment_2026.pdf', size: 524288, type: 'application/pdf' }], links: [], uploadedAt: '2026-06-15T10:00:00Z', updatedAt: '2026-06-15T10:00:00Z' },
  { id: genId(), title: 'SOC 2 Type II Report', type: 'certificate', framework: 'SOC 2', status: 'active', files: [{ name: 'SOC2_Report_2025.pdf', size: 1048576, type: 'application/pdf' }], links: [], uploadedAt: '2025-12-01T10:00:00Z', updatedAt: '2025-12-01T10:00:00Z' },
  { id: genId(), title: 'BCP Test Results Q2', type: 'evidence', framework: 'NBU Resolution №143', status: 'active', files: [], links: ['https://novapay-bcm/test-results-q2'], uploadedAt: '2026-06-20T10:00:00Z', updatedAt: '2026-06-20T10:00:00Z' },
  { id: genId(), title: 'Data Processing Register', type: 'procedure', framework: 'GDPR', status: 'active', files: [{ name: 'RoPA_v2.xlsx', size: 102400, type: 'application/xlsx' }], links: ['https://novapay-privacy/ropa'], uploadedAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z' },
  { id: genId(), title: 'Penetration Test Report Q1 2026', type: 'report', framework: 'PCI DSS', status: 'active', files: [{ name: 'PT_Report_Q1_2026.pdf', size: 2097152, type: 'application/pdf' }], links: [], uploadedAt: '2026-03-15T10:00:00Z', updatedAt: '2026-03-15T10:00:00Z' },
  { id: genId(), title: 'ISO 27001 Certificate', type: 'certificate', framework: 'ISO 27001', status: 'active', files: [{ name: 'ISO27001_Cert.pdf', size: 512000, type: 'application/pdf' }], links: [], uploadedAt: '2025-06-01T10:00:00Z', updatedAt: '2025-06-01T10:00:00Z' },
  { id: genId(), title: 'Incident Response Playbooks', type: 'procedure', framework: 'NIST CSF', status: 'active', files: [{ name: 'IR_Playbooks_v2.docx', size: 307200, type: 'application/docx' }], links: ['https://novapay-siem/playbooks'], uploadedAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-01T10:00:00Z' },
];

const SEED_INTEGRATIONS: Integration[] = [
  { id: genId(), name: 'AWS', type: 'Cloud', connectorType: 'aws', status: 'connected', config: { awsAccessKeyId: 'AKIA****WXYZ', awsRegion: 'eu-west-1', awsRoleArn: 'arn:aws:iam::123456789012:role/grc-scanner' }, lastSync: '2026-07-02T06:00:00Z', version: '1.0.0' },
  { id: genId(), name: 'GitHub', type: 'Code Repository', connectorType: 'github', status: 'connected', config: { githubOrganization: 'novapay', githubRepository: 'novapay-core' }, lastSync: '2026-07-02T06:30:00Z', version: '1.0.0' },
  { id: genId(), name: 'GitLab', type: 'Code Repository', connectorType: 'gitlab', status: 'disconnected', config: { gitlabUrl: 'https://gitlab.novapay.ua', gitlabProjectId: '42' }, lastSync: '', version: '0.9.0' },
  { id: genId(), name: 'Microsoft 365', type: 'Productivity', connectorType: 'm365', status: 'disconnected', config: { m365TenantId: 'contoso.onmicrosoft.com' }, lastSync: '2026-06-28T10:00:00Z', version: '1.1.0' },
  { id: genId(), name: 'Azure', type: 'Cloud', connectorType: 'azure', status: 'connected', config: { azureTenantId: '550e8400-e29b-41d4-a716-446655440000', azureSubscriptionId: 'subscription-id', azureClientId: 'app-id' }, lastSync: '2026-07-02T06:00:00Z', version: '1.0.0' },
  { id: genId(), name: 'Jira', type: 'Project Management', connectorType: 'jira', status: 'connected', config: { jiraUrl: 'https://novapay.atlassian.net', jiraProject: 'SEC' }, lastSync: '2026-07-02T06:00:00Z', version: '1.0.0' },
  { id: genId(), name: 'Google Spaces', type: 'Productivity', connectorType: 'google_spaces', status: 'connected', config: { googleSpacesDomain: 'novapay.ua' }, lastSync: '2026-07-02T06:00:00Z', version: '0.8.0' },
  { id: genId(), name: 'GCP', type: 'Cloud', connectorType: 'gcp', status: 'connected', config: { gcpProjectId: 'novapay-prod', gcpRegion: 'europe-west1' }, lastSync: '2026-07-02T05:00:00Z', version: '1.0.0' },
];

function loadFromStorage<T>(key: string, fallback: T): T {
  try { const d = localStorage.getItem(key); return d ? JSON.parse(d) : fallback; } catch { return fallback; }
}

export function ComplianceProvider({ children }: { children: ReactNode }) {
  const [tasks, setTasks] = useState<GRCTask[]>(() => loadFromStorage('grc-tasks', SEED_TASKS));
  const [controls, setControls] = useState<GRCControl[]>([]);
  const [controlsLoaded, setControlsLoaded] = useState(false);
  const [policies, setPolicies] = useState<Policy[]>(() => loadFromStorage('grc-policies', SEED_POLICIES));
  const [documents, setDocuments] = useState<GRCDocument[]>(() => loadFromStorage('grc-documents', SEED_DOCUMENTS));
  const [checks, setChecks] = useState<AutomatedCheck[]>(() => loadFromStorage('grc-checks', SEED_CHECKS));
  const [milestones, setMilestones] = useState<Milestone[]>(() => loadFromStorage('grc-milestones', SEED_MILESTONES));
  const [integrations, setIntegrations] = useState<Integration[]>(() => loadFromStorage('grc-integrations', SEED_INTEGRATIONS));
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);

  useEffect(() => { localStorage.setItem('grc-tasks', JSON.stringify(tasks)); }, [tasks]);
  useEffect(() => {
    apiFetch('/api/controls')
      .then(res => res.ok ? res.json() : Promise.reject(new Error('Failed to load controls')))
      .then((data: GRCControl[]) => {
        setControls(data);
        setControlsLoaded(true);
      })
      .catch(() => {
        setControls(loadFromStorage('grc-controls', SEED_CONTROLS));
        setControlsLoaded(true);
      });
  }, []);
  useEffect(() => { if (controlsLoaded) localStorage.setItem('grc-controls', JSON.stringify(controls)); }, [controls, controlsLoaded]);
  useEffect(() => { localStorage.setItem('grc-policies', JSON.stringify(policies)); }, [policies]);
  useEffect(() => { localStorage.setItem('grc-documents', JSON.stringify(documents)); }, [documents]);
  useEffect(() => { localStorage.setItem('grc-checks', JSON.stringify(checks)); }, [checks]);
  useEffect(() => { localStorage.setItem('grc-milestones', JSON.stringify(milestones)); }, [milestones]);
  useEffect(() => { localStorage.setItem('grc-integrations', JSON.stringify(integrations)); }, [integrations]);

  const addTask = useCallback((d: Omit<GRCTask, 'id' | 'createdAt' | 'updatedAt'>) => {
    const now = new Date().toISOString();
    const created = { ...d, id: genId(), createdAt: now, updatedAt: now } as GRCTask;
    setTasks(prev => [created, ...prev]);
    return created;
  }, []);
  const updateTask = useCallback((id: string, d: Partial<GRCTask>) => setTasks(prev => prev.map(t => t.id === id ? { ...t, ...d, updatedAt: new Date().toISOString() } : t)), []);
  const deleteTask = useCallback((id: string) => setTasks(prev => prev.filter(t => t.id !== id)), []);

  const addControl = useCallback(async (d: Omit<GRCControl, 'id' | 'createdAt' | 'updatedAt'>) => {
    try {
      const res = await apiFetch('/api/controls', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(d),
      });
      if (res.ok) {
        const created = await res.json() as GRCControl;
        setControls(prev => [created, ...prev]);
        return;
      }
    } catch { /* fallback below */ }
    const now = new Date().toISOString();
    setControls(prev => [{ ...d, id: genId(), createdAt: now, updatedAt: now } as GRCControl, ...prev]);
  }, []);
  const updateControl = useCallback(async (id: string, d: Partial<GRCControl>) => {
    try {
      const res = await apiFetch(`/api/controls/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(d),
      });
      if (res.ok) {
        const updated = await res.json() as GRCControl;
        setControls(prev => prev.map(c => c.id === id ? updated : c));
        return;
      }
    } catch { /* fallback below */ }
    setControls(prev => prev.map(c => c.id === id ? { ...c, ...d, updatedAt: new Date().toISOString() } : c));
  }, []);
  const deleteControl = useCallback(async (id: string) => {
    try {
      const res = await apiFetch(`/api/controls/${id}`, { method: 'DELETE' });
      if (res.ok || res.status === 204) {
        setControls(prev => prev.filter(c => c.id !== id));
        return;
      }
    } catch { /* fallback below */ }
    setControls(prev => prev.filter(c => c.id !== id));
  }, []);

  const addPolicy = useCallback((d: Omit<Policy, 'id' | 'createdAt' | 'updatedAt'>) => {
    const now = new Date().toISOString();
    setPolicies(prev => [{ ...d, id: genId(), createdAt: now, updatedAt: now } as Policy, ...prev]);
  }, []);
  const updatePolicy = useCallback((id: string, d: Partial<Policy>) => setPolicies(prev => prev.map(p => p.id === id ? { ...p, ...d, updatedAt: new Date().toISOString() } : p)), []);
  const deletePolicy = useCallback((id: string) => setPolicies(prev => prev.filter(p => p.id !== id)), []);

  const addDocument = useCallback((d: Omit<GRCDocument, 'id'>) => setDocuments(prev => [{ ...d, id: genId() } as GRCDocument, ...prev]), []);
  const deleteDocument = useCallback((id: string) => setDocuments(prev => prev.filter(d => d.id !== id)), []);

  const addMilestone = useCallback((d: Omit<Milestone, 'id'>) => setMilestones(prev => [{ ...d, id: genId() } as Milestone, ...prev]), []);
  const updateMilestone = useCallback((id: string, d: Partial<Milestone>) => setMilestones(prev => prev.map(m => m.id === id ? { ...m, ...d } : m)), []);

  const updateIntegration = useCallback((id: string, d: Partial<Integration>) => setIntegrations(prev => prev.map(i => i.id === id ? { ...i, ...d } : i)), []);

  const addChatMessage = useCallback((d: Omit<ChatMessage, 'id' | 'timestamp'>) => {
    setChatMessages(prev => [...prev, { ...d, id: genId(), timestamp: new Date().toISOString() } as ChatMessage]);
  }, []);
  const clearChat = useCallback(() => setChatMessages([]), []);

  return (
    <ComplianceContext.Provider value={{
      tasks, controls, policies, documents, checks, milestones, integrations, chatMessages,
      addTask, updateTask, deleteTask,
      addControl, updateControl, deleteControl,
      addPolicy, updatePolicy, deletePolicy,
      addDocument, deleteDocument,
      addMilestone, updateMilestone,
      updateIntegration,
      addChatMessage, clearChat,
    }}>
      {children}
    </ComplianceContext.Provider>
  );
}

export function useCompliance() {
  const ctx = useContext(ComplianceContext);
  if (!ctx) throw new Error('useCompliance must be used within ComplianceProvider');
  return ctx;
}
